image:
  repository: ghcr.io/bcgov/vdyp-liquibase
  tag: latest
  pullPolicy: IfNotPresent

# Where your Crunchy cluster is
crunchy:
  # PGO creates a Secret named like: <cluster>-pguser-<dbname>
  pguserSecretName: crunchy-postgres-#{ENV}#-pguser-#{VDYP_ADMIN_USER}#
  # Point at primary service for DDL. If you must use PgBouncer, set it here and ensure session pooling.
  host: crunchy-postgres-#{ENV}#-primary.default.svc.cluster.local
  port: 5432
  database: #VDYP_DB_NAME#

liquibase:
  defaultSchema: "#{VDYP_ADMIN_USER}#"   # quote in changelog when needed
  logLevel: debug
  command: "update"           # or "status", "updateSql" for dry-run
  extraArgs: []               # e.g., ["--rollback-on-error=true"]

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

job:
  backoffLimit: 2
  ttlSecondsAfterFinished: 1800
