apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "liquibase.fullname" . }}
  labels:
    {{- include "liquibase.labels" . | nindent 4 }}
spec:
  backoffLimit: {{ .Values.job.backoffLimit }}
  ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished }}
  template:
    metadata:
      labels:
        {{- include "liquibase.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: vdyp-liquibase-#{ENV}#
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            # Pull credentials from the PGO-created secret
            - name: ENV_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.crunchy.pguserSecretName }}
                  key: password
            - name: ENV_DB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.crunchy.pguserSecretName }}
                  key: jdbc-uri
            - name: ENV_DB_DBNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.crunchy.pguserSecretName }}
                  key: dbname
            - name: ENV_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.crunchy.pguserSecretName }}
                  key: port
            - name: ENV_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.crunchy.pguserSecretName }}
                  key: host
            - name: ENV_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.crunchy.pguserSecretName }}
                  key: host
          command: ["/bin/sh","-c"]
          args:
            - |
              export PGPASSWORD="${ENV_DB_PASSWORD}"
              echo "Waiting for PostgreSQL at ${ENV_DB_HOST}:${ENV_DB_PORT}..."
              for i in $(seq 1 60); do
                if /usr/bin/env pg_isready -h ${ENV_DB_HOST} -p ${ENV_DB_PORT} -d ${ENV_DB_DBNAME} >/dev/null 2>&1; then
                  break
                fi
                sleep 2
              done
              
              echo "Running Liquibase {{ .Values.liquibase.command }}..."
              liquibase \
                --log-level={{ .Values.liquibase.logLevel }} \
                --url="${ENV_DB_URI}&currentSchema=%22app-vdyp%22" \
                {{- range .Values.liquibase.extraArgs }}
                {{ . }} \
                {{- end }}
                {{ .Values.liquibase.command }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

