apiVersion: v1
kind: Secret
metadata:
  name: vdyp-liquibase-#{ENV}#-pguser-vdyp-proxy-password
  labels: {{- include "labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  password: #{POSTGRESQL_VDYP_PROXY_PASSWORD}#
