export enum ExecutionOptionsEnum {
  BackGrowEnabled = 'backGrowEnabled',
  ForwardGrowEnabled = 'forwardGrowEnabled',
  DoSaveIntermediateFiles = 'doSaveIntermediateFiles',
  DoForceReferenceYearInclusionInYieldTables = 'doForceReferenceYearInclusionInYieldTables',
  DoForceCurrentYearInclusionInYieldTables = 'doForceCurrentYearInclusionInYieldTables',
  DoIncludeFileHeader = 'doIncludeFileHeader',
  DoIncludeProjectionModeInYieldTable = 'doIncludeProjectionModeInYieldTable',
  DoIncludeAgeRowsInYieldTable = 'doIncludeAgeRowsInYieldTable',
  DoIncludeYearRowsInYieldTable = 'doIncludeYearRowsInYieldTable',
  DoIncludePolygonRecordIdInYieldTable = 'doIncludePolygonRecordIdInYieldTable',
  DoSummarizeProjectionByPolygon = 'doSummarizeProjectionByPolygon',
  DoSummarizeProjectionByLayer = 'doSummarizeProjectionByLayer',
  DoIncludeSpeciesProjection = 'doIncludeSpeciesProjection',
  DoIncludeProjectedMOFVolumes = 'doIncludeProjectedMOFVolumes',
  DoIncludeProjectedMOFBiomass = 'doIncludeProjectedMOFBiomass',
  DoIncludeProjectedCFSBiomass = 'doIncludeProjectedCFSBiomass',
  DoIncludeColumnHeadersInYieldTable = 'doIncludeColumnHeadersInYieldTable',
  DoAllowBasalAreaAndTreesPerHectareValueSubstitution = 'doAllowBasalAreaAndTreesPerHectareValueSubstitution',
  DoIncludeSecondarySpeciesDominantHeightInYieldTable = 'doIncludeSecondarySpeciesDominantHeightInYieldTable',
  DoEnableProgressLogging = 'doEnableProgressLogging',
  DoEnableErrorLogging = 'doEnableErrorLogging',
  DoEnableDebugLogging = 'doEnableDebugLogging',
  AllowAggressiveValueEstimation = 'allowAggressiveValueEstimation',
  DoIncludeProjectionFiles = 'doIncludeProjectionFiles',
  DoDelayExecutionFolderDeletion = 'doDelayExecutionFolderDeletion',
}
