/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 19-Aug-2025 11:40:15 AM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "app_nrs_vdyp"."batch_job" CASCADE
;

DROP TABLE IF EXISTS "app_nrs_vdyp"."calculation_engine_code" CASCADE
;

DROP TABLE IF EXISTS "app_nrs_vdyp"."coms_object" CASCADE
;

DROP TABLE IF EXISTS "app_nrs_vdyp"."file_mapping" CASCADE
;

DROP TABLE IF EXISTS "app_nrs_vdyp"."file_set" CASCADE
;

DROP TABLE IF EXISTS "app_nrs_vdyp"."file_set_type_code" CASCADE
;

DROP TABLE IF EXISTS "app_nrs_vdyp"."projection" CASCADE
;

DROP TABLE IF EXISTS "app_nrs_vdyp"."projection_batch_mapping" CASCADE
;

DROP TABLE IF EXISTS "app_nrs_vdyp"."projection_parameter_pres" CASCADE
;

DROP TABLE IF EXISTS "app_nrs_vdyp"."projection_status_code" CASCADE
;

DROP TABLE IF EXISTS "app_nrs_vdyp"."user" CASCADE
;

DROP TABLE IF EXISTS "app_nrs_vdyp"."user_type_code" CASCADE
;

/* Create Tables */

CREATE TABLE "app_nrs_vdyp"."batch_job"
(
	"batch_job_guid" UUID NOT NULL,    -- batch_job_guid is a unique identifier for the record.
	"revision_count" decimal(10) NOT NULL   DEFAULT 0,    -- REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.
	"create_user" varchar(64) NOT NULL,    -- CREATE_USER is an audit column that indicates the user that created the record.
	"create_date" DATE NOT NULL   DEFAULT CURRENT_TIMESTAMP,    -- CREATE_DATE is the date and time the row of data was created.
	"update_user" varchar(64) NOT NULL,    -- UPDATE_USER is an audit column that indicates the user that updated the record.
	"update_date" DATE NOT NULL   DEFAULT CURRENT_TIMESTAMP    -- UPDATE_DATE is the date and time the row of data was updated.
)
TABLESPACE	PG_DEFAULT
;

CREATE TABLE "app_nrs_vdyp"."calculation_engine_code"
(
	"calculation_engine_code" varchar(10) NOT NULL,    -- calculation_engine_code: Calculation Engine Code is a future proofing aggregation of versions of individual internal components Values are: - 8.0 
	"description" varchar(200) NOT NULL,    -- DESCRIPTION is the display quality description of the code value.
	"display_order" decimal(3) NULL,    -- DISPLAY ORDER is to allow non alphabetic sorting e.g. M T W Th F S S.
	"effective_date" DATE NOT NULL   DEFAULT CURRENT_DATE,    -- EFFECTIVE_DATE is the date code value becomes effective.
	"expiry_date" DATE NOT NULL   DEFAULT '9999-12-31',    -- EXPIRY_DATE is the date code value expires.
	"revision_count" decimal(10) NOT NULL   DEFAULT 0,    -- REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.
	"create_user" varchar(64) NOT NULL,    -- CREATE_USER is an audit column that indicates the user that created the record.
	"create_date" DATE NOT NULL   DEFAULT CURRENT_TIMESTAMP,    -- CREATE_DATE is the date and time the row of data was created.
	"update_user" varchar(64) NOT NULL,    -- UPDATE_USER is an audit column that indicates the user that updated the record.
	"update_date" DATE NOT NULL   DEFAULT CURRENT_TIMESTAMP    -- UPDATE_DATE is the date and time the row of data was updated.
)
TABLESPACE	PG_DEFAULT
;

CREATE TABLE "app_nrs_vdyp"."coms_object"
(
	"coms_object_guid" UUID NOT NULL,    -- coms_object_guid is a unique identifier for the record.
	"revision_count" decimal(10) NOT NULL   DEFAULT 0,    -- REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.
	"create_user" varchar(64) NOT NULL,    -- CREATE_USER is an audit column that indicates the user that created the record.
	"create_date" DATE NOT NULL   DEFAULT CURRENT_TIMESTAMP,    -- CREATE_DATE is the date and time the row of data was created.
	"update_user" varchar(64) NOT NULL,    -- UPDATE_USER is an audit column that indicates the user that updated the record.
	"update_date" DATE NOT NULL   DEFAULT CURRENT_TIMESTAMP    -- UPDATE_DATE is the date and time the row of data was updated.
)
TABLESPACE	PG_DEFAULT
;

CREATE TABLE "app_nrs_vdyp"."file_mapping"
(
	"file_mapping_guid" UUID NOT NULL,    -- file_mapping_guid is a unique identifier for the record.
	"coms_object_guid" UUID NOT NULL,    -- coms_object_guid: Is a foreign key to coms_object: Object is an Object in the COMS microservice.
	"file_set_guid" UUID NOT NULL,    -- file_set_guid: Is a foreign key to file_set: File Set is a group of Files that can be used in a projection. This will handle groups of Polygon files, groups of Layer files and groups of Result files.
	"revision_count" decimal(10) NOT NULL   DEFAULT 0,    -- REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.
	"create_user" varchar(64) NOT NULL,    -- CREATE_USER is an audit column that indicates the user that created the record.
	"create_date" DATE NOT NULL   DEFAULT CURRENT_TIMESTAMP,    -- CREATE_DATE is the date and time the row of data was created.
	"update_user" varchar(64) NOT NULL,    -- UPDATE_USER is an audit column that indicates the user that updated the record.
	"update_date" DATE NOT NULL   DEFAULT CURRENT_TIMESTAMP    -- UPDATE_DATE is the date and time the row of data was updated.
)
TABLESPACE	PG_DEFAULT
;

CREATE TABLE "app_nrs_vdyp"."file_set"
(
	"file_set_guid" UUID NOT NULL,    -- file_set_guid is a unique identifier for the record.
	"user_guid" UUID NOT NULL,    -- user_guid: Is a foreign key to user: User is used to track profiles for users that access the VDYP system
	"file_set_type_code" varchar(10) NOT NULL,    -- file_set_type_code: Is a foreign key to file_set_type_code: File Set Type Code is the mode that the file set will be used. Values are: - Polygon - Layer - Result
	"file_set_name" varchar(4000) NULL,    -- File Set Name is a short description of the files contained in the set
	"description" varchar(4000) NULL,    -- Description is a long description of the files contained in the set
	"revision_count" decimal(10) NOT NULL   DEFAULT 0,    -- REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.
	"create_user" varchar(64) NOT NULL,    -- CREATE_USER is an audit column that indicates the user that created the record.
	"create_date" DATE NOT NULL   DEFAULT CURRENT_TIMESTAMP,    -- CREATE_DATE is the date and time the row of data was created.
	"update_user" varchar(64) NOT NULL,    -- UPDATE_USER is an audit column that indicates the user that updated the record.
	"update_date" DATE NOT NULL   DEFAULT CURRENT_TIMESTAMP    -- UPDATE_DATE is the date and time the row of data was updated.
)
TABLESPACE	PG_DEFAULT
;

CREATE TABLE "app_nrs_vdyp"."file_set_type_code"
(
	"file_set_type_code" varchar(10) NOT NULL,    -- file_set_type_code: File Set Type Code is the mode that the file set will be used. Values are: - Polygon - Layer - Result
	"description" varchar(200) NOT NULL,    -- DESCRIPTION is the display quality description of the code value.
	"display_order" decimal(3) NULL,    -- DISPLAY ORDER is to allow non alphabetic sorting e.g. M T W Th F S S.
	"effective_date" DATE NOT NULL   DEFAULT CURRENT_DATE,    -- EFFECTIVE_DATE is the date code value becomes effective.
	"expiry_date" DATE NOT NULL   DEFAULT '9999-12-31',    -- EXPIRY_DATE is the date code value expires.
	"revision_count" decimal(10) NOT NULL   DEFAULT 0,    -- REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.
	"create_user" varchar(64) NOT NULL,    -- CREATE_USER is an audit column that indicates the user that created the record.
	"create_date" DATE NOT NULL   DEFAULT CURRENT_TIMESTAMP,    -- CREATE_DATE is the date and time the row of data was created.
	"update_user" varchar(64) NOT NULL,    -- UPDATE_USER is an audit column that indicates the user that updated the record.
	"update_date" DATE NOT NULL   DEFAULT CURRENT_TIMESTAMP    -- UPDATE_DATE is the date and time the row of data was updated.
)
TABLESPACE	PG_DEFAULT
;

CREATE TABLE "app_nrs_vdyp"."projection"
(
	"projection_guid" UUID NOT NULL,    -- projection_guid is a unique identifier for the record.
	"layer_file_set_guid" UUID NOT NULL,    -- LAYER_file_set_guid: Is a foreign key to file_set: File Set is a group of Files that can be used in a projection. This will handle groups of Polygon files, groups of Layer files and groups of Result files.
	"polygon_file_set_guid" UUID NOT NULL,    -- POLYGON_file_set_guid: Is a foreign key to file_set: File Set is a group of Files that can be used in a projection. This will handle groups of Polygon files, groups of Layer files and groups of Result files.
	"calculation_engine_code" varchar(10) NOT NULL,    -- calculation_engine_code: Is a foreign key to calculation_engine_code: Calculation Engine Code is a future proofing aggregation of versions of individual internal components Values are: - 8.0 
	"user_guid" UUID NOT NULL,    -- user_guid: Is a foreign key to user: User is used to track profiles for users that access the VDYP system
	"projection_status_code" varchar(10) NOT NULL,    -- projection_status_code: Is a foreign key to projection_status_code: Projection Status Code is the current status of the projection. Values are: - Draft - Queued - Started - Completed - Canceled
	"result_file_set_guid" UUID NOT NULL,    -- RESULT_file_set_guid: Is a foreign key to file_set: File Set is a group of Files that can be used in a projection. This will handle groups of Polygon files, groups of Layer files and groups of Result files.
	"vdyp_parameters" varchar(1000) NOT NULL,    -- VDYP Parameters is a JSON encoded string containing all parameters required to run this projection
	"start_date" TIMESTAMP NULL,    -- Start Date is the date the projection processing was started
	"end_date" TIMESTAMP NULL,    -- End date is the date the projection completed processing
	"revision_count" decimal(10) NOT NULL   DEFAULT 0,    -- REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.
	"create_user" varchar(64) NOT NULL,    -- CREATE_USER is an audit column that indicates the user that created the record.
	"create_date" DATE NOT NULL   DEFAULT CURRENT_TIMESTAMP,    -- CREATE_DATE is the date and time the row of data was created.
	"update_user" varchar(64) NOT NULL,    -- UPDATE_USER is an audit column that indicates the user that updated the record.
	"update_date" DATE NOT NULL   DEFAULT CURRENT_TIMESTAMP    -- UPDATE_DATE is the date and time the row of data was updated.
)
TABLESPACE	PG_DEFAULT
;

CREATE TABLE "app_nrs_vdyp"."projection_batch_mapping"
(
	"projection_batch_mapping_guid" UUID NOT NULL,    -- projection_batch_mapping_guid is a unique identifier for the record.
	"batch_job_guid" UUID NOT NULL,    -- batch_job_guid: Is a foreign key to batch_job: Batch Job is a projections entry in the Batch Job System
	"projection_guid" UUID NOT NULL,    -- projection_guid: Is a foreign key to projection: Projection Parameters is a collection of all the inputs used to create a VDYP projection including, a Polygon File Set, a Layer File Set, and a JSON encoded string of parameters 
	"partitions" INT NOT NULL,    -- Partitions is the number of partitions that the batch job has created for the mapped projection
	"completed_partitions" INT NOT NULL,    -- Completed Partitions is the number of partitions the batch system is reporting as completed 
	"errors" INT NOT NULL,    -- Errors is the number of errors reported during processing
	"warnings" INT NOT NULL,    -- Warnings is the number of warnings reported during processing
	"revision_count" decimal(10) NOT NULL   DEFAULT 0,    -- REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.
	"create_user" varchar(64) NOT NULL,    -- CREATE_USER is an audit column that indicates the user that created the record.
	"create_date" DATE NOT NULL   DEFAULT CURRENT_TIMESTAMP,    -- CREATE_DATE is the date and time the row of data was created.
	"update_user" varchar(64) NOT NULL,    -- UPDATE_USER is an audit column that indicates the user that updated the record.
	"update_date" DATE NOT NULL   DEFAULT CURRENT_TIMESTAMP    -- UPDATE_DATE is the date and time the row of data was updated.
)
TABLESPACE	PG_DEFAULT
;

CREATE TABLE "app_nrs_vdyp"."projection_parameter_pres"
(
	"projection_parameter_pres_guid" UUID NOT NULL,    -- projection_parameter_pres_guid is a unique identifier for the record.
	"user_guid" UUID NOT NULL,    -- user_guid: Is a foreign key to user: User is used to track profiles for users that access the VDYP system
	"preset_name" varchar(4000) NOT NULL,    -- Preset Name is a short description of the presets for user reference
	"parameters" varchar(4000) NOT NULL,    -- Parameters is a JSON string that represetns the parameters that this preset saves
	"revision_count" decimal(10) NOT NULL   DEFAULT 0,    -- REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.
	"create_user" varchar(64) NOT NULL,    -- CREATE_USER is an audit column that indicates the user that created the record.
	"create_date" DATE NOT NULL   DEFAULT CURRENT_TIMESTAMP,    -- CREATE_DATE is the date and time the row of data was created.
	"update_user" varchar(64) NOT NULL,    -- UPDATE_USER is an audit column that indicates the user that updated the record.
	"update_date" DATE NOT NULL   DEFAULT CURRENT_TIMESTAMP    -- UPDATE_DATE is the date and time the row of data was updated.
)
TABLESPACE	PG_DEFAULT
;

CREATE TABLE "app_nrs_vdyp"."projection_status_code"
(
	"projection_status_code" varchar(10) NOT NULL,    -- projection_status_code: Projection Status Code is the current status of the projection. Values are: - Draft - Queued - Started - Completed - Canceled
	"description" varchar(200) NOT NULL,    -- DESCRIPTION is the display quality description of the code value.
	"display_order" decimal(3) NULL,    -- DISPLAY ORDER is to allow non alphabetic sorting e.g. M T W Th F S S.
	"effective_date" DATE NOT NULL   DEFAULT CURRENT_DATE,    -- EFFECTIVE_DATE is the date code value becomes effective.
	"expiry_date" DATE NOT NULL   DEFAULT '9999-12-31',    -- EXPIRY_DATE is the date code value expires.
	"revision_count" decimal(10) NOT NULL   DEFAULT 0,    -- REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.
	"create_user" varchar(64) NOT NULL,    -- CREATE_USER is an audit column that indicates the user that created the record.
	"create_date" DATE NOT NULL   DEFAULT CURRENT_TIMESTAMP,    -- CREATE_DATE is the date and time the row of data was created.
	"update_user" varchar(64) NOT NULL,    -- UPDATE_USER is an audit column that indicates the user that updated the record.
	"update_date" DATE NOT NULL   DEFAULT CURRENT_TIMESTAMP    -- UPDATE_DATE is the date and time the row of data was updated.
)
TABLESPACE	PG_DEFAULT
;

CREATE TABLE "app_nrs_vdyp"."user"
(
	"user_guid" UUID NOT NULL,    -- user_guid is a unique identifier for the record.
	"oidc_id" varchar(100) NOT NULL,    -- OpenID Connect ID is the Identifier for this profile that is profided from the Bc Government Single Sign On Service to identify this user as unique.
	"user_type_code" varchar(10) NOT NULL,    -- user_type_code: Is a foreign key to user_type_code: User Type Code is a code representing an access level for a user profile  Values are: - Admin - Super User - User
	"first_name" varchar(50) NOT NULL,    -- First Name is the first name of the user that this profile corresponds to
	"last_name" varchar(50) NOT NULL,    -- Last Name is the first name of the user that this profile corresponds to
	"revision_count" decimal(10) NOT NULL   DEFAULT 0,    -- REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.
	"create_user" varchar(64) NOT NULL,    -- CREATE_USER is an audit column that indicates the user that created the record.
	"create_date" DATE NOT NULL   DEFAULT CURRENT_TIMESTAMP,    -- CREATE_DATE is the date and time the row of data was created.
	"update_user" varchar(64) NOT NULL,    -- UPDATE_USER is an audit column that indicates the user that updated the record.
	"update_date" DATE NOT NULL   DEFAULT CURRENT_TIMESTAMP    -- UPDATE_DATE is the date and time the row of data was updated.
)
TABLESPACE	PG_DEFAULT
;

CREATE TABLE "app_nrs_vdyp"."user_type_code"
(
	"user_type_code" varchar(10) NOT NULL,    -- user_type_code: User Type Code is a code representing an access level for a user profile  Values are: - Admin - Super User - User
	"description" varchar(200) NOT NULL,    -- DESCRIPTION is the display quality description of the code value.
	"display_order" decimal(3) NULL,    -- DISPLAY ORDER is to allow non alphabetic sorting e.g. M T W Th F S S.
	"effective_date" DATE NOT NULL   DEFAULT CURRENT_DATE,    -- EFFECTIVE_DATE is the date code value becomes effective.
	"expiry_date" DATE NOT NULL   DEFAULT '9999-12-31',    -- EXPIRY_DATE is the date code value expires.
	"revision_count" decimal(10) NOT NULL   DEFAULT 0,    -- REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.
	"create_user" varchar(64) NOT NULL,    -- CREATE_USER is an audit column that indicates the user that created the record.
	"create_date" DATE NOT NULL   DEFAULT CURRENT_TIMESTAMP,    -- CREATE_DATE is the date and time the row of data was created.
	"update_user" varchar(64) NOT NULL,    -- UPDATE_USER is an audit column that indicates the user that updated the record.
	"update_date" DATE NOT NULL   DEFAULT CURRENT_TIMESTAMP    -- UPDATE_DATE is the date and time the row of data was updated.
)
TABLESPACE	PG_DEFAULT
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "app_nrs_vdyp"."batch_job" ADD CONSTRAINT "batch_jo_pk"
	PRIMARY KEY ("batch_job_guid")
;

ALTER TABLE "app_nrs_vdyp"."calculation_engine_code" ADD CONSTRAINT "calc_eng_pk"
	PRIMARY KEY ("calculation_engine_code")
;

ALTER TABLE "app_nrs_vdyp"."coms_object" ADD CONSTRAINT "coms_obj_pk"
	PRIMARY KEY ("coms_object_guid")
;

ALTER TABLE "app_nrs_vdyp"."file_mapping" ADD CONSTRAINT "filemap_pk"
	PRIMARY KEY ("file_mapping_guid")
;

ALTER TABLE "app_nrs_vdyp"."file_mapping" ADD CONSTRAINT "filemap_uk" UNIQUE ("coms_object_guid","file_set_guid")
;

CREATE INDEX "filemap_coms_obj_idx" ON "app_nrs_vdyp"."file_mapping" ("coms_object_guid" ASC)
;

CREATE INDEX "filemap_fileset_idx" ON "app_nrs_vdyp"."file_mapping" ("file_set_guid" ASC)
;

ALTER TABLE "app_nrs_vdyp"."file_set" ADD CONSTRAINT "fileset_pk"
	PRIMARY KEY ("file_set_guid")
;

CREATE INDEX "fileset_user_idx" ON "app_nrs_vdyp"."file_set" ("user_guid" ASC)
;

CREATE INDEX "fileset_flsttype_idx" ON "app_nrs_vdyp"."file_set" ("file_set_type_code" ASC)
;

ALTER TABLE "app_nrs_vdyp"."file_set_type_code" ADD CONSTRAINT "flsttype_pk"
	PRIMARY KEY ("file_set_type_code")
;

ALTER TABLE "app_nrs_vdyp"."projection" ADD CONSTRAINT "prjctn_pk"
	PRIMARY KEY ("projection_guid")
;

CREATE INDEX "prjctn_fileset_layer_idx" ON "app_nrs_vdyp"."projection" ("layer_file_set_guid" ASC)
;

CREATE INDEX "prjctn_fileset_polygon_idx" ON "app_nrs_vdyp"."projection" ("polygon_file_set_guid" ASC)
;

CREATE INDEX "prjctn_calc_eng_idx" ON "app_nrs_vdyp"."projection" ("calculation_engine_code" ASC)
;

CREATE INDEX "prjctn_user_idx" ON "app_nrs_vdyp"."projection" ("user_guid" ASC)
;

CREATE INDEX "prjctn_prjstat_idx" ON "app_nrs_vdyp"."projection" ("projection_status_code" ASC)
;

CREATE INDEX "prjctn_fileset_result_idx" ON "app_nrs_vdyp"."projection" ("result_file_set_guid" ASC)
;

ALTER TABLE "app_nrs_vdyp"."projection_batch_mapping" ADD CONSTRAINT "prjbatmap_pk"
	PRIMARY KEY ("projection_batch_mapping_guid")
;

ALTER TABLE "app_nrs_vdyp"."projection_batch_mapping" ADD CONSTRAINT "prjbatmap_uk" UNIQUE ("batch_job_guid","projection_guid")
;

CREATE INDEX "prjbatmap_batch_jo_idx" ON "app_nrs_vdyp"."projection_batch_mapping" ("batch_job_guid" ASC)
;

CREATE INDEX "prjbatmap_prjctn_idx" ON "app_nrs_vdyp"."projection_batch_mapping" ("projection_guid" ASC)
;

ALTER TABLE "app_nrs_vdyp"."projection_parameter_pres" ADD CONSTRAINT "prjprmpr_pk"
	PRIMARY KEY ("projection_parameter_pres_guid")
;

CREATE INDEX "prjprmpr_user_idx" ON "app_nrs_vdyp"."projection_parameter_pres" ("user_guid" ASC)
;

ALTER TABLE "app_nrs_vdyp"."projection_status_code" ADD CONSTRAINT "prjstat_pk"
	PRIMARY KEY ("projection_status_code")
;

ALTER TABLE "app_nrs_vdyp"."user" ADD CONSTRAINT "user_pk"
	PRIMARY KEY ("user_guid")
;

ALTER TABLE "app_nrs_vdyp"."user" ADD CONSTRAINT "user_uk" UNIQUE ("oidc_id")
;

CREATE INDEX "user_usertype_idx" ON "app_nrs_vdyp"."user" ("user_type_code" ASC)
;

ALTER TABLE "app_nrs_vdyp"."user_type_code" ADD CONSTRAINT "usertype_pk"
	PRIMARY KEY ("user_type_code")
;

/* Create Foreign Key Constraints */

ALTER TABLE "app_nrs_vdyp"."file_mapping" ADD CONSTRAINT "filemap_coms_obj_fk"
	FOREIGN KEY ("coms_object_guid") REFERENCES "app_nrs_vdyp"."coms_object" ("coms_object_guid") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "app_nrs_vdyp"."file_mapping" ADD CONSTRAINT "filemap_fileset_fk"
	FOREIGN KEY ("file_set_guid") REFERENCES "app_nrs_vdyp"."file_set" ("file_set_guid") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "app_nrs_vdyp"."file_set" ADD CONSTRAINT "fileset_user_fk"
	FOREIGN KEY ("user_guid") REFERENCES "app_nrs_vdyp"."user" ("user_guid") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "app_nrs_vdyp"."file_set" ADD CONSTRAINT "fileset_flsttype_fk"
	FOREIGN KEY ("file_set_type_code") REFERENCES "app_nrs_vdyp"."file_set_type_code" ("file_set_type_code") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "app_nrs_vdyp"."projection" ADD CONSTRAINT "prjctn_fileset_layer_fk"
	FOREIGN KEY ("layer_file_set_guid") REFERENCES "app_nrs_vdyp"."file_set" ("file_set_guid") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "app_nrs_vdyp"."projection" ADD CONSTRAINT "prjctn_fileset_polygon_fk"
	FOREIGN KEY ("polygon_file_set_guid") REFERENCES "app_nrs_vdyp"."file_set" ("file_set_guid") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "app_nrs_vdyp"."projection" ADD CONSTRAINT "prjctn_calc_eng_fk"
	FOREIGN KEY ("calculation_engine_code") REFERENCES "app_nrs_vdyp"."calculation_engine_code" ("calculation_engine_code") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "app_nrs_vdyp"."projection" ADD CONSTRAINT "prjctn_user_fk"
	FOREIGN KEY ("user_guid") REFERENCES "app_nrs_vdyp"."user" ("user_guid") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "app_nrs_vdyp"."projection" ADD CONSTRAINT "prjctn_prjstat_fk"
	FOREIGN KEY ("projection_status_code") REFERENCES "app_nrs_vdyp"."projection_status_code" ("projection_status_code") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "app_nrs_vdyp"."projection" ADD CONSTRAINT "prjctn_fileset_result_fk"
	FOREIGN KEY ("result_file_set_guid") REFERENCES "app_nrs_vdyp"."file_set" ("file_set_guid") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "app_nrs_vdyp"."projection_batch_mapping" ADD CONSTRAINT "prjbatmap_batch_jo_fk"
	FOREIGN KEY ("batch_job_guid") REFERENCES "app_nrs_vdyp"."batch_job" ("batch_job_guid") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "app_nrs_vdyp"."projection_batch_mapping" ADD CONSTRAINT "prjbatmap_prjctn_fk"
	FOREIGN KEY ("projection_guid") REFERENCES "app_nrs_vdyp"."projection" ("projection_guid") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "app_nrs_vdyp"."projection_parameter_pres" ADD CONSTRAINT "prjprmpr_user_fk"
	FOREIGN KEY ("user_guid") REFERENCES "app_nrs_vdyp"."user" ("user_guid") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "app_nrs_vdyp"."user" ADD CONSTRAINT "user_usertype_fk"
	FOREIGN KEY ("user_type_code") REFERENCES "app_nrs_vdyp"."user_type_code" ("user_type_code") ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "app_nrs_vdyp"."batch_job"
	IS 'Batch Job is a projections entry in the Batch Job System'
;

COMMENT ON COLUMN "app_nrs_vdyp"."batch_job"."batch_job_guid"
	IS 'batch_job_guid is a unique identifier for the record.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."batch_job"."revision_count"
	IS 'REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."batch_job"."create_user"
	IS 'CREATE_USER is an audit column that indicates the user that created the record.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."batch_job"."create_date"
	IS 'CREATE_DATE is the date and time the row of data was created.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."batch_job"."update_user"
	IS 'UPDATE_USER is an audit column that indicates the user that updated the record.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."batch_job"."update_date"
	IS 'UPDATE_DATE is the date and time the row of data was updated.'
;

COMMENT ON TABLE "app_nrs_vdyp"."calculation_engine_code"
	IS 'Calculation Engine Code is a future proofing aggregation of versions of individual internal components Values are: - 8.0 '
;

COMMENT ON COLUMN "app_nrs_vdyp"."calculation_engine_code"."calculation_engine_code"
	IS 'calculation_engine_code: Calculation Engine Code is a future proofing aggregation of versions of individual internal components Values are: - 8.0 '
;

COMMENT ON COLUMN "app_nrs_vdyp"."calculation_engine_code"."description"
	IS 'DESCRIPTION is the display quality description of the code value.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."calculation_engine_code"."display_order"
	IS 'DISPLAY ORDER is to allow non alphabetic sorting e.g. M T W Th F S S.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."calculation_engine_code"."effective_date"
	IS 'EFFECTIVE_DATE is the date code value becomes effective.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."calculation_engine_code"."expiry_date"
	IS 'EXPIRY_DATE is the date code value expires.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."calculation_engine_code"."revision_count"
	IS 'REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."calculation_engine_code"."create_user"
	IS 'CREATE_USER is an audit column that indicates the user that created the record.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."calculation_engine_code"."create_date"
	IS 'CREATE_DATE is the date and time the row of data was created.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."calculation_engine_code"."update_user"
	IS 'UPDATE_USER is an audit column that indicates the user that updated the record.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."calculation_engine_code"."update_date"
	IS 'UPDATE_DATE is the date and time the row of data was updated.'
;

COMMENT ON TABLE "app_nrs_vdyp"."coms_object"
	IS 'Object is an Object in the COMS microservice.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."coms_object"."coms_object_guid"
	IS 'coms_object_guid is a unique identifier for the record.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."coms_object"."revision_count"
	IS 'REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."coms_object"."create_user"
	IS 'CREATE_USER is an audit column that indicates the user that created the record.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."coms_object"."create_date"
	IS 'CREATE_DATE is the date and time the row of data was created.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."coms_object"."update_user"
	IS 'UPDATE_USER is an audit column that indicates the user that updated the record.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."coms_object"."update_date"
	IS 'UPDATE_DATE is the date and time the row of data was updated.'
;

COMMENT ON TABLE "app_nrs_vdyp"."file_mapping"
	IS 'File is a mapping of an object in the COMS system to a File Set in VDYP'
;

COMMENT ON COLUMN "app_nrs_vdyp"."file_mapping"."file_mapping_guid"
	IS 'file_mapping_guid is a unique identifier for the record.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."file_mapping"."coms_object_guid"
	IS 'coms_object_guid: Is a foreign key to coms_object: Object is an Object in the COMS microservice.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."file_mapping"."file_set_guid"
	IS 'file_set_guid: Is a foreign key to file_set: File Set is a group of Files that can be used in a projection. This will handle groups of Polygon files, groups of Layer files and groups of Result files.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."file_mapping"."revision_count"
	IS 'REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."file_mapping"."create_user"
	IS 'CREATE_USER is an audit column that indicates the user that created the record.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."file_mapping"."create_date"
	IS 'CREATE_DATE is the date and time the row of data was created.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."file_mapping"."update_user"
	IS 'UPDATE_USER is an audit column that indicates the user that updated the record.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."file_mapping"."update_date"
	IS 'UPDATE_DATE is the date and time the row of data was updated.'
;

COMMENT ON TABLE "app_nrs_vdyp"."file_set"
	IS 'File Set is a group of Files that can be used in a projection. This will handle groups of Polygon files, groups of Layer files and groups of Result files.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."file_set"."file_set_guid"
	IS 'file_set_guid is a unique identifier for the record.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."file_set"."user_guid"
	IS 'user_guid: Is a foreign key to user: User is used to track profiles for users that access the VDYP system'
;

COMMENT ON COLUMN "app_nrs_vdyp"."file_set"."file_set_type_code"
	IS 'file_set_type_code: Is a foreign key to file_set_type_code: File Set Type Code is the mode that the file set will be used. Values are: - Polygon - Layer - Result'
;

COMMENT ON COLUMN "app_nrs_vdyp"."file_set"."file_set_name"
	IS 'File Set Name is a short description of the files contained in the set'
;

COMMENT ON COLUMN "app_nrs_vdyp"."file_set"."description"
	IS 'Description is a long description of the files contained in the set'
;

COMMENT ON COLUMN "app_nrs_vdyp"."file_set"."revision_count"
	IS 'REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."file_set"."create_user"
	IS 'CREATE_USER is an audit column that indicates the user that created the record.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."file_set"."create_date"
	IS 'CREATE_DATE is the date and time the row of data was created.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."file_set"."update_user"
	IS 'UPDATE_USER is an audit column that indicates the user that updated the record.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."file_set"."update_date"
	IS 'UPDATE_DATE is the date and time the row of data was updated.'
;

COMMENT ON TABLE "app_nrs_vdyp"."file_set_type_code"
	IS 'File Set Type Code is the mode that the file set will be used. Values are: - Polygon - Layer - Result'
;

COMMENT ON COLUMN "app_nrs_vdyp"."file_set_type_code"."file_set_type_code"
	IS 'file_set_type_code: File Set Type Code is the mode that the file set will be used. Values are: - Polygon - Layer - Result'
;

COMMENT ON COLUMN "app_nrs_vdyp"."file_set_type_code"."description"
	IS 'DESCRIPTION is the display quality description of the code value.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."file_set_type_code"."display_order"
	IS 'DISPLAY ORDER is to allow non alphabetic sorting e.g. M T W Th F S S.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."file_set_type_code"."effective_date"
	IS 'EFFECTIVE_DATE is the date code value becomes effective.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."file_set_type_code"."expiry_date"
	IS 'EXPIRY_DATE is the date code value expires.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."file_set_type_code"."revision_count"
	IS 'REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."file_set_type_code"."create_user"
	IS 'CREATE_USER is an audit column that indicates the user that created the record.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."file_set_type_code"."create_date"
	IS 'CREATE_DATE is the date and time the row of data was created.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."file_set_type_code"."update_user"
	IS 'UPDATE_USER is an audit column that indicates the user that updated the record.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."file_set_type_code"."update_date"
	IS 'UPDATE_DATE is the date and time the row of data was updated.'
;

COMMENT ON TABLE "app_nrs_vdyp"."projection"
	IS 'Projection Parameters is a collection of all the inputs used to create a VDYP projection including, a Polygon File Set, a Layer File Set, and a JSON encoded string of parameters '
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection"."projection_guid"
	IS 'projection_guid is a unique identifier for the record.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection"."layer_file_set_guid"
	IS 'LAYER_file_set_guid: Is a foreign key to file_set: File Set is a group of Files that can be used in a projection. This will handle groups of Polygon files, groups of Layer files and groups of Result files.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection"."polygon_file_set_guid"
	IS 'POLYGON_file_set_guid: Is a foreign key to file_set: File Set is a group of Files that can be used in a projection. This will handle groups of Polygon files, groups of Layer files and groups of Result files.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection"."calculation_engine_code"
	IS 'calculation_engine_code: Is a foreign key to calculation_engine_code: Calculation Engine Code is a future proofing aggregation of versions of individual internal components Values are: - 8.0 '
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection"."user_guid"
	IS 'user_guid: Is a foreign key to user: User is used to track profiles for users that access the VDYP system'
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection"."projection_status_code"
	IS 'projection_status_code: Is a foreign key to projection_status_code: Projection Status Code is the current status of the projection. Values are: - Draft - Queued - Started - Completed - Canceled'
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection"."result_file_set_guid"
	IS 'RESULT_file_set_guid: Is a foreign key to file_set: File Set is a group of Files that can be used in a projection. This will handle groups of Polygon files, groups of Layer files and groups of Result files.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection"."vdyp_parameters"
	IS 'VDYP Parameters is a JSON encoded string containing all parameters required to run this projection'
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection"."start_date"
	IS 'Start Date is the date the projection processing was started'
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection"."end_date"
	IS 'End date is the date the projection completed processing'
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection"."revision_count"
	IS 'REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection"."create_user"
	IS 'CREATE_USER is an audit column that indicates the user that created the record.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection"."create_date"
	IS 'CREATE_DATE is the date and time the row of data was created.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection"."update_user"
	IS 'UPDATE_USER is an audit column that indicates the user that updated the record.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection"."update_date"
	IS 'UPDATE_DATE is the date and time the row of data was updated.'
;

COMMENT ON TABLE "app_nrs_vdyp"."projection_batch_mapping"
	IS 'Projection Batch Mapping is a mapping of internal projections to external batch system GUID along with details that are only updated by the batch system'
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection_batch_mapping"."projection_batch_mapping_guid"
	IS 'projection_batch_mapping_guid is a unique identifier for the record.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection_batch_mapping"."batch_job_guid"
	IS 'batch_job_guid: Is a foreign key to batch_job: Batch Job is a projections entry in the Batch Job System'
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection_batch_mapping"."projection_guid"
	IS 'projection_guid: Is a foreign key to projection: Projection Parameters is a collection of all the inputs used to create a VDYP projection including, a Polygon File Set, a Layer File Set, and a JSON encoded string of parameters '
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection_batch_mapping"."partitions"
	IS 'Partitions is the number of partitions that the batch job has created for the mapped projection'
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection_batch_mapping"."completed_partitions"
	IS 'Completed Partitions is the number of partitions the batch system is reporting as completed '
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection_batch_mapping"."errors"
	IS 'Errors is the number of errors reported during processing'
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection_batch_mapping"."warnings"
	IS 'Warnings is the number of warnings reported during processing'
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection_batch_mapping"."revision_count"
	IS 'REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection_batch_mapping"."create_user"
	IS 'CREATE_USER is an audit column that indicates the user that created the record.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection_batch_mapping"."create_date"
	IS 'CREATE_DATE is the date and time the row of data was created.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection_batch_mapping"."update_user"
	IS 'UPDATE_USER is an audit column that indicates the user that updated the record.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection_batch_mapping"."update_date"
	IS 'UPDATE_DATE is the date and time the row of data was updated.'
;

COMMENT ON TABLE "app_nrs_vdyp"."projection_parameter_pres"
	IS 'Projection Parameter Preset is a saved copy of the JSON Parameters to run a projection.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection_parameter_pres"."projection_parameter_pres_guid"
	IS 'projection_parameter_pres_guid is a unique identifier for the record.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection_parameter_pres"."user_guid"
	IS 'user_guid: Is a foreign key to user: User is used to track profiles for users that access the VDYP system'
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection_parameter_pres"."preset_name"
	IS 'Preset Name is a short description of the presets for user reference'
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection_parameter_pres"."parameters"
	IS 'Parameters is a JSON string that represetns the parameters that this preset saves'
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection_parameter_pres"."revision_count"
	IS 'REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection_parameter_pres"."create_user"
	IS 'CREATE_USER is an audit column that indicates the user that created the record.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection_parameter_pres"."create_date"
	IS 'CREATE_DATE is the date and time the row of data was created.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection_parameter_pres"."update_user"
	IS 'UPDATE_USER is an audit column that indicates the user that updated the record.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection_parameter_pres"."update_date"
	IS 'UPDATE_DATE is the date and time the row of data was updated.'
;

COMMENT ON TABLE "app_nrs_vdyp"."projection_status_code"
	IS 'Projection Status Code is the current status of the projection. Values are: - Draft - Queued - Started - Completed - Canceled'
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection_status_code"."projection_status_code"
	IS 'projection_status_code: Projection Status Code is the current status of the projection. Values are: - Draft - Queued - Started - Completed - Canceled'
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection_status_code"."description"
	IS 'DESCRIPTION is the display quality description of the code value.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection_status_code"."display_order"
	IS 'DISPLAY ORDER is to allow non alphabetic sorting e.g. M T W Th F S S.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection_status_code"."effective_date"
	IS 'EFFECTIVE_DATE is the date code value becomes effective.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection_status_code"."expiry_date"
	IS 'EXPIRY_DATE is the date code value expires.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection_status_code"."revision_count"
	IS 'REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection_status_code"."create_user"
	IS 'CREATE_USER is an audit column that indicates the user that created the record.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection_status_code"."create_date"
	IS 'CREATE_DATE is the date and time the row of data was created.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection_status_code"."update_user"
	IS 'UPDATE_USER is an audit column that indicates the user that updated the record.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."projection_status_code"."update_date"
	IS 'UPDATE_DATE is the date and time the row of data was updated.'
;

COMMENT ON TABLE "app_nrs_vdyp"."user"
	IS 'User is used to track profiles for users that access the VDYP system'
;

COMMENT ON COLUMN "app_nrs_vdyp"."user"."user_guid"
	IS 'user_guid is a unique identifier for the record.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."user"."oidc_id"
	IS 'OpenID Connect ID is the Identifier for this profile that is profided from the Bc Government Single Sign On Service to identify this user as unique.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."user"."user_type_code"
	IS 'user_type_code: Is a foreign key to user_type_code: User Type Code is a code representing an access level for a user profile  Values are: - Admin - Super User - User'
;

COMMENT ON COLUMN "app_nrs_vdyp"."user"."first_name"
	IS 'First Name is the first name of the user that this profile corresponds to'
;

COMMENT ON COLUMN "app_nrs_vdyp"."user"."last_name"
	IS 'Last Name is the first name of the user that this profile corresponds to'
;

COMMENT ON COLUMN "app_nrs_vdyp"."user"."revision_count"
	IS 'REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."user"."create_user"
	IS 'CREATE_USER is an audit column that indicates the user that created the record.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."user"."create_date"
	IS 'CREATE_DATE is the date and time the row of data was created.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."user"."update_user"
	IS 'UPDATE_USER is an audit column that indicates the user that updated the record.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."user"."update_date"
	IS 'UPDATE_DATE is the date and time the row of data was updated.'
;

COMMENT ON TABLE "app_nrs_vdyp"."user_type_code"
	IS 'User Type Code is a code representing an access level for a user profile  Values are: - Admin - Super User - User'
;

COMMENT ON COLUMN "app_nrs_vdyp"."user_type_code"."user_type_code"
	IS 'user_type_code: User Type Code is a code representing an access level for a user profile  Values are: - Admin - Super User - User'
;

COMMENT ON COLUMN "app_nrs_vdyp"."user_type_code"."description"
	IS 'DESCRIPTION is the display quality description of the code value.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."user_type_code"."display_order"
	IS 'DISPLAY ORDER is to allow non alphabetic sorting e.g. M T W Th F S S.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."user_type_code"."effective_date"
	IS 'EFFECTIVE_DATE is the date code value becomes effective.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."user_type_code"."expiry_date"
	IS 'EXPIRY_DATE is the date code value expires.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."user_type_code"."revision_count"
	IS 'REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."user_type_code"."create_user"
	IS 'CREATE_USER is an audit column that indicates the user that created the record.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."user_type_code"."create_date"
	IS 'CREATE_DATE is the date and time the row of data was created.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."user_type_code"."update_user"
	IS 'UPDATE_USER is an audit column that indicates the user that updated the record.'
;

COMMENT ON COLUMN "app_nrs_vdyp"."user_type_code"."update_date"
	IS 'UPDATE_DATE is the date and time the row of data was updated.'
;
