package ca.bc.gov.nrs.vdyp.backend.projection.model.enumerations;

public enum ReturnCode {
	
	SUCCESS(0), //
	ERROR_INTERNALERROR(-1), //
	ERROR_INVALIDPARAMETER(-2), //
	ERROR_CORELIBRARYERROR(-3), //
	ERROR_INVALIDBEC(-4), //
	ERROR_LAYERNOTFOUND(-5), //
	ERROR_LAYERALREADYEXISTS(-6), //
	ERROR_TOOMANYLAYERS(-7), //
	ERROR_INVALIDSPECIES(-8), //
	ERROR_SPECIESALREADYEXISTS(-9), //
	ERROR_SPECIESNOTFOUND(-10), //
	ERROR_TOOMANYSPECIES(-11), //
	ERROR_INVALIDUTILLEVEL(-12), //
	ERROR_INCORRECTSTATE(-13), //
	ERROR_PERCENTNOT100(-14), //
	ERROR_POLYGONNONPRODUCTIVE(-15), //
	ERROR_RANK1ALREADYEXISTS(-16), //
	ERROR_INVALIDSTANDADJUSTMENT(-17), //
	ERROR_INVALIDSITEINFO(-18), //
	ERROR_LAYERNOTPROCESSED(-19);

	public final int errorCode;
	
	private ReturnCode(int errorCode) {
		this.errorCode = errorCode;
	}
}
