/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 23-Oct-2025 9:36:17 AM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */
/* Drop  CONSTRAINT "fileset_uk" UNIQUE ("vdyp_user_guid") */
ALTER TABLE "app-vdyp"."projection_file_set" DROP CONSTRAINT "fileset_uk"
;
