/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 23-Oct-2025 9:36:17 AM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop CONSTRAINT "prjprmpr_uk" UNIQUE ("vdyp_user_guid")*/

ALTER TABLE "app-vdyp"."projection_param_preset" DROP CONSTRAINT "prjprmpr_uk"
;
