/*
 * Variable Density Yield Projection
 * API for the Variable Density Yield Projection service
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package ca.bc.gov.nrs.vdyp.backend.projection;

import static ca.bc.gov.nrs.vdyp.backend.model.v1.Parameters.ExecutionOption.DO_ALLOW_BASAL_AREA_AND_TREES_PER_HECTARE_VALUE_SUBSTITUTION;
import static ca.bc.gov.nrs.vdyp.backend.model.v1.Parameters.ExecutionOption.DO_INCLUDE_AGE_ROWS_IN_YIELD_TABLE;
import static ca.bc.gov.nrs.vdyp.backend.model.v1.Parameters.ExecutionOption.DO_INCLUDE_COLUMN_HEADERS_IN_YIELD_TABLE;
import static ca.bc.gov.nrs.vdyp.backend.model.v1.Parameters.ExecutionOption.DO_INCLUDE_FILE_HEADER;
import static ca.bc.gov.nrs.vdyp.backend.model.v1.Parameters.ExecutionOption.DO_INCLUDE_PROJECTED_MOF_VOLUMES;
import static ca.bc.gov.nrs.vdyp.backend.model.v1.Parameters.ExecutionOption.DO_INCLUDE_PROJECTION_MODE_IN_YIELD_TABLE;
import static ca.bc.gov.nrs.vdyp.backend.model.v1.Parameters.ExecutionOption.DO_INCLUDE_YEAR_ROWS_IN_YIELD_TABLE;
import static ca.bc.gov.nrs.vdyp.backend.model.v1.Parameters.ExecutionOption.DO_SUMMARIZE_PROJECTION_BY_LAYER;
import static ca.bc.gov.nrs.vdyp.backend.model.v1.Parameters.ExecutionOption.FORWARD_GROW_ENABLED;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;

import ca.bc.gov.nrs.vdyp.backend.model.v1.Filters;
import ca.bc.gov.nrs.vdyp.backend.model.v1.ProgressFrequency;
import ca.bc.gov.nrs.vdyp.backend.model.v1.Parameters.AgeYearRangeCombinationKind;
import ca.bc.gov.nrs.vdyp.backend.model.v1.Parameters.MetadataToOutputDirective;
import ca.bc.gov.nrs.vdyp.backend.model.v1.Parameters.OutputFormat;
import ca.bc.gov.nrs.vdyp.backend.model.v1.Parameters.DebugOption;
import ca.bc.gov.nrs.vdyp.backend.model.v1.Parameters.ExecutionOption;
import io.quarkus.runtime.annotations.RegisterForReflection;

/**
 * This class represents a Parameters instance that has been validated. All fields are converted to their internal data
 * type (if not String). All defaults have been applied.
 */
@RegisterForReflection
public class ValidatedParameters {

	public static final ValidatedParameters DEFAULT;

	private OutputFormat outputFormat;
	private List<ExecutionOption> selectedExecutionOptions = new ArrayList<>();
	private List<DebugOption> selectedDebugOptions = new ArrayList<>();
	private Integer ageStart;
	private Integer minAgeStart;
	private Integer maxAgeStart;
	private Integer ageEnd;
	private Integer minAgeEnd;
	private Integer maxAgeEnd;
	private Integer yearStart;
	private Integer minYearStart;
	private Integer maxYearStart;
	private Integer yearEnd;
	private Integer minYearEnd;
	private Integer maxYearEnd;
	private Integer forceYear;
	private Integer ageIncrement;
	private Integer minAgeIncrement;
	private Integer maxAgeIncrement;
	private AgeYearRangeCombinationKind combineAgeYearRange;
	private ProgressFrequency progressFrequency;
	private MetadataToOutputDirective metadataToOutput;
	private Filters filters;
	private List<ValidatedUtilizationParameter> utils = new ArrayList<>();

	/**
	 * Helper method that returns "true" iff the given option is in <code>selectedExecutionOptions</code>.
	 *
	 * @param option the option whose presence is determined
	 * @return as described
	 */
	public boolean containsOption(ExecutionOption option) {
		return selectedExecutionOptions.contains(option);
	}

	/**
	 * Helper method that returns "true" iff the given option is in <code>selectedDebugOptions</code>.
	 *
	 * @param option the option whose presence is determined
	 * @return as described
	 */
	public boolean containsOption(DebugOption option) {
		return selectedDebugOptions.contains(option);
	}

	public ValidatedParameters outputFormat(OutputFormat outputFormat) {
		this.outputFormat = outputFormat;
		return this;
	}

	/**
	 * Identifies the output file format. Default: YieldTable
	 *
	 * @return outputFormat
	 */
	public OutputFormat getOutputFormat() {
		return outputFormat;
	}

	public void setOutputFormat(OutputFormat outputFormat) {
		this.outputFormat = outputFormat;
	}

	public ValidatedParameters selectedExecutionOptions(List<ExecutionOption> selectedExecutionOptions) {
		this.selectedExecutionOptions = selectedExecutionOptions;
		return this;
	}

	public ValidatedParameters
			addSelectedExecutionOptionsItem(ExecutionOption selectedExecutionOptionsItem) {
		if (this.selectedExecutionOptions == null) {
			this.selectedExecutionOptions = new ArrayList<>();
		}
		this.selectedExecutionOptions.add(selectedExecutionOptionsItem);
		return this;
	}

	/**
	 * Get selectedExecutionOptions
	 *
	 * @return selectedExecutionOptions
	 */
	public List<ExecutionOption> getSelectedExecutionOptions() {
		return Collections.unmodifiableList(selectedExecutionOptions);
	}

	public void setSelectedExecutionOptions(List<ExecutionOption> selectedExecutionOptions) {
		this.selectedExecutionOptions = selectedExecutionOptions;
	}

	public ValidatedParameters selectedDebugOptions(List<DebugOption> selectedDebugOptions) {
		this.selectedDebugOptions = selectedDebugOptions;
		return this;
	}

	public ValidatedParameters addSelectedDebugOptionsItem(DebugOption selectedDebugOptionsItem) {
		if (this.selectedDebugOptions == null) {
			this.selectedDebugOptions = new ArrayList<>();
		}
		this.selectedDebugOptions.add(selectedDebugOptionsItem);
		return this;
	}

	/**
	 * Get selectedDebugOptions
	 *
	 * @return selectedDebugOptions
	 */
	public List<DebugOption> getSelectedDebugOptions() {
		return Collections.unmodifiableList(selectedDebugOptions);
	}

	public void setSelectedDebugOptions(List<DebugOption> selectedDebugOptions) {
		this.selectedDebugOptions = selectedDebugOptions;
	}

	public ValidatedParameters ageStart(Integer ageStart) {
		this.ageStart = ageStart;
		return this;
	}

	/**
	 * The starting age value for the Age Range for generated yield tables.
	 *
	 * @return ageStart
	 */
	public Integer getAgeStart() {
		return ageStart;
	}

	public void setAgeStart(Integer ageStart) {
		this.ageStart = ageStart;
	}

	ValidatedParameters minAgeStart(Integer minAgeStart) {
		this.minAgeStart = minAgeStart;
		return this;
	}

	Integer getMinAgeStart() {
		return minAgeStart;
	}

	void setMinAgeStart(Integer minAgeStart) {
		this.minAgeStart = minAgeStart;
	}

	ValidatedParameters maxAgeStart(Integer maxAgeStart) {
		this.maxAgeStart = maxAgeStart;
		return this;
	}

	Integer getMaxAgeStart() {
		return maxAgeStart;
	}

	void setMaxAgeStart(Integer maxAgeStart) {
		this.maxAgeStart = maxAgeStart;
	}

	public ValidatedParameters ageEnd(Integer ageEnd) {
		this.ageEnd = ageEnd;
		return this;
	}

	/**
	 * The ending age value for the Age Range for generated yield tables.
	 *
	 * @return ageEnd
	 */
	public Integer getAgeEnd() {
		return ageEnd;
	}

	public void setAgeEnd(Integer ageEnd) {
		this.ageEnd = ageEnd;
	}

	ValidatedParameters minAgeEnd(Integer minAgeEnd) {
		this.minAgeEnd = minAgeEnd;
		return this;
	}

	Integer getMinAgeEnd() {
		return minAgeEnd;
	}

	void setMinAgeEnd(Integer minAgeEnd) {
		this.minAgeEnd = minAgeEnd;
	}

	ValidatedParameters maxAgeEnd(Integer maxAgeEnd) {
		this.maxAgeEnd = maxAgeEnd;
		return this;
	}

	Integer getMaxAgeEnd() {
		return maxAgeEnd;
	}

	void setMaxAgeEnd(Integer maxAgeEnd) {
		this.maxAgeEnd = maxAgeEnd;
	}

	public ValidatedParameters yearStart(Integer yearStart) {
		this.yearStart = yearStart;
		return this;
	}

	/**
	 * The starting year for the Year Range for generated yield tables.
	 *
	 * @return yearStart
	 */
	public Integer getYearStart() {
		return yearStart;
	}

	public void setYearStart(Integer yearStart) {
		this.yearStart = yearStart;
	}

	ValidatedParameters minYearStart(Integer minYearStart) {
		this.minYearStart = minYearStart;
		return this;
	}

	Integer getMinYearStart() {
		return minYearStart;
	}

	void setMinYearStart(Integer minYearStart) {
		this.minYearStart = minYearStart;
	}

	ValidatedParameters maxYearStart(Integer maxYearStart) {
		this.maxYearStart = maxYearStart;
		return this;
	}

	Integer getMaxYearStart() {
		return maxYearStart;
	}

	void setMaxYearStart(Integer maxYearStart) {
		this.maxYearStart = maxYearStart;
	}

	public ValidatedParameters yearEnd(Integer yearEnd) {
		this.yearEnd = yearEnd;
		return this;
	}

	/**
	 * The ending year for the Year Range for generated yield tables.
	 *
	 * @return yearEnd
	 */
	public Integer getYearEnd() {
		return yearEnd;
	}

	public void setYearEnd(Integer yearEnd) {
		this.yearEnd = yearEnd;
	}

	ValidatedParameters minYearEnd(Integer minYearEnd) {
		this.minYearEnd = minYearEnd;
		return this;
	}

	Integer getMinYearEnd() {
		return minYearEnd;
	}

	void setMinYearEnd(Integer minYearEnd) {
		this.minYearEnd = minYearEnd;
	}

	ValidatedParameters maxYearEnd(Integer maxYearEnd) {
		this.maxYearEnd = maxYearEnd;
		return this;
	}

	Integer getMaxYearEnd() {
		return maxYearEnd;
	}

	void setMaxYearEnd(Integer maxYearEnd) {
		this.maxYearEnd = maxYearEnd;
	}

	public ValidatedParameters forceYear(Integer forceYear) {
		this.forceYear = forceYear;
		return this;
	}

	/**
	 * Forces the inclusion of the specified calendar year in Yield tables.
	 *
	 * @return forceYear
	 */
	public Integer getForceYear() {
		return forceYear;
	}

	public void setForceYear(Integer forceYear) {
		this.forceYear = forceYear;
	}

	public ValidatedParameters ageIncrement(Integer ageIncrement) {
		this.ageIncrement = ageIncrement;
		return this;
	}

	/**
	 * The number of years to increment the current value for the Age and Year ranges.
	 *
	 * @return ageIncrement
	 */
	public Integer getAgeIncrement() {
		return ageIncrement;
	}

	public void setAgeIncrement(Integer ageIncrement) {
		this.ageIncrement = ageIncrement;
	}

	public ValidatedParameters minAgeIncrement(Integer minAgeIncrement) {
		this.minAgeIncrement = minAgeIncrement;
		return this;
	}

	/**
	 * The minimum value ageIncrement may have.
	 *
	 * @return minAgeIncrement
	 */
	public Integer getMinAgeIncrement() {
		return minAgeIncrement;
	}

	public void setMinAgeIncrement(Integer minAgeIncrement) {
		this.minAgeIncrement = minAgeIncrement;
	}

	public ValidatedParameters maxAgeIncrement(Integer maxAgeIncrement) {
		this.maxAgeIncrement = maxAgeIncrement;
		return this;
	}

	/**
	 * The maximum value ageIncrement may have.
	 *
	 * @return maxAgeIncrement
	 */
	public Integer getMaxAgeIncrement() {
		return maxAgeIncrement;
	}

	public void setMaxAgeIncrement(Integer maxAgeIncrement) {
		this.maxAgeIncrement = maxAgeIncrement;
	}

	public ValidatedParameters combineAgeYearRange(AgeYearRangeCombinationKind combineAgeYearRange) {
		this.combineAgeYearRange = combineAgeYearRange;
		return this;
	}

	/**
	 * Determines how the Age Range and Year Range are to be combined when producing yield tables.
	 *
	 * @return combineAgeYearRange
	 */
	public AgeYearRangeCombinationKind getCombineAgeYearRange() {
		return combineAgeYearRange;
	}

	public void setCombineAgeYearRange(AgeYearRangeCombinationKind combineAgeYearRange) {
		this.combineAgeYearRange = combineAgeYearRange;
	}

	public ValidatedParameters progressFrequency(ProgressFrequency progressFrequency) {
		this.progressFrequency = progressFrequency;
		return this;
	}

	/**
	 * Get progressFrequency
	 *
	 * @return progressFrequency
	 */
	public ProgressFrequency getProgressFrequency() {
		return progressFrequency;
	}

	public void setProgressFrequency(ProgressFrequency progressFrequency) {
		this.progressFrequency = progressFrequency.copy();
	}

	public ValidatedParameters metadataToOutput(MetadataToOutputDirective metadataToOutput) {
		this.metadataToOutput = metadataToOutput;
		return this;
	}

	/**
	 * Controls how much metadata is displayed in the Output and Error Logs.
	 *
	 * @return metadataToOutput
	 */
	public MetadataToOutputDirective getMetadataToOutput() {
		return metadataToOutput;
	}

	public void setMetadataToOutput(MetadataToOutputDirective metadataToOutput) {
		this.metadataToOutput = metadataToOutput;
	}

	public ValidatedParameters filters(Filters filters) {
		this.filters = filters;
		return this;
	}

	/**
	 * Get filters
	 *
	 * @return filters
	 */
	public Filters getFilters() {
		return filters;
	}

	public void setFilters(Filters filters) {
		this.filters = filters;
	}

	public ValidatedParameters utils(List<ValidatedUtilizationParameter> utils) {
		this.utils = utils;
		return this;
	}

	public ValidatedParameters addUtilsItem(ValidatedUtilizationParameter utilsItem) {
		if (this.utils == null) {
			this.utils = new ArrayList<>();
		}
		this.utils.add(utilsItem);
		return this;
	}

	/**
	 * Get utils
	 *
	 * @return utils
	 */
	public List<ValidatedUtilizationParameter> getUtils() {
		return Collections.unmodifiableList(utils);
	}

	public void setUtils(List<ValidatedUtilizationParameter> utils) {
		this.utils = utils;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		ValidatedParameters parameters = (ValidatedParameters) o;
		return Objects.equals(this.outputFormat, parameters.outputFormat)
				&& Objects.equals(this.selectedExecutionOptions, parameters.selectedExecutionOptions)
				&& Objects.equals(this.selectedDebugOptions, parameters.selectedDebugOptions)
				&& Objects.equals(this.ageStart, parameters.ageStart)
				&& Objects.equals(this.minAgeStart, parameters.minAgeStart)
				&& Objects.equals(this.maxAgeStart, parameters.maxAgeStart)
				&& Objects.equals(this.ageEnd, parameters.ageEnd)
				&& Objects.equals(this.minAgeEnd, parameters.minAgeEnd)
				&& Objects.equals(this.maxAgeEnd, parameters.maxAgeEnd)
				&& Objects.equals(this.yearStart, parameters.yearStart)
				&& Objects.equals(this.yearEnd, parameters.yearEnd)
				&& Objects.equals(this.forceYear, parameters.forceYear)
				&& Objects.equals(this.ageIncrement, parameters.ageIncrement)
				&& Objects.equals(this.minAgeIncrement, parameters.minAgeIncrement)
				&& Objects.equals(this.maxAgeIncrement, parameters.maxAgeIncrement)
				&& Objects.equals(this.combineAgeYearRange, parameters.combineAgeYearRange)
				&& Objects.equals(this.progressFrequency, parameters.progressFrequency)
				&& Objects.equals(this.metadataToOutput, parameters.metadataToOutput)
				&& Objects.equals(this.filters, parameters.filters) //
				&& Objects.equals(this.utils, parameters.utils);
	}

	@Override
	public int hashCode() {
		return Objects.hash(
				outputFormat, selectedExecutionOptions, selectedDebugOptions, ageStart, minAgeStart, maxAgeStart,
				ageEnd, minAgeEnd, maxAgeEnd, yearStart, yearEnd, forceYear, ageIncrement, minAgeIncrement,
				maxAgeIncrement, combineAgeYearRange, progressFrequency, metadataToOutput, utils
		);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class Parameters {\n");

		sb.append("    outputFormat: ").append(toIndentedString(outputFormat)).append("\n");
		sb.append("    selectedExecutionOptions: ").append(toIndentedString(selectedExecutionOptions)).append("\n");
		sb.append("    selectedDebugOptions: ").append(toIndentedString(selectedDebugOptions)).append("\n");
		sb.append("    ageStart: ").append(toIndentedString(ageStart)).append("\n");
		sb.append("    minAgeStart: ").append(toIndentedString(minAgeStart)).append("\n");
		sb.append("    maxAgeStart: ").append(toIndentedString(maxAgeStart)).append("\n");
		sb.append("    ageEnd: ").append(toIndentedString(ageEnd)).append("\n");
		sb.append("    minAgeEnd: ").append(toIndentedString(minAgeEnd)).append("\n");
		sb.append("    maxAgeEnd: ").append(toIndentedString(maxAgeEnd)).append("\n");
		sb.append("    yearStart: ").append(toIndentedString(yearStart)).append("\n");
		sb.append("    yearEnd: ").append(toIndentedString(yearEnd)).append("\n");
		sb.append("    forceYear: ").append(toIndentedString(forceYear)).append("\n");
		sb.append("    ageIncrement: ").append(toIndentedString(ageIncrement)).append("\n");
		sb.append("    minAgeIncrement: ").append(toIndentedString(minAgeIncrement)).append("\n");
		sb.append("    maxAgeIncrement: ").append(toIndentedString(maxAgeIncrement)).append("\n");
		sb.append("    combineAgeYearRange: ").append(toIndentedString(combineAgeYearRange)).append("\n");
		sb.append("    progressFrequency: ").append(toIndentedString(progressFrequency)).append("\n");
		sb.append("    metadataToOutput: ").append(toIndentedString(metadataToOutput)).append("\n");
		sb.append("    filters: ").append(toIndentedString(filters)).append("\n");
		sb.append("    utils: ").append(toIndentedString(utils)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	static {
		DEFAULT = new ValidatedParameters();

		DEFAULT.ageStart = null;
		DEFAULT.ageEnd = null;
		DEFAULT.yearStart = null;
		DEFAULT.yearEnd = null;
		DEFAULT.ageIncrement = null;

		DEFAULT.outputFormat = OutputFormat.CSV_YIELD_TABLE;

		DEFAULT.selectedExecutionOptions = new ArrayList<>();
		// exclude since false: BACK_GROW_ENABLED
		DEFAULT.selectedExecutionOptions.add(FORWARD_GROW_ENABLED);
		// exclude since false: DO_SAVE_INTERMEDIATE_FILES
		// exclude since false: DO_FORCE_REFERENCE_YEAR_INCLUSION_IN_YIELD_TABLES
		// exclude since false: DO_FORCE_CURRENT_YEAR_INCLUSION_IN_YIELD_TABLES
		// exclude since false: DO_FORCE_CALENDAR_YEAR_INCLUSION_IN_YIELD_TABLES
		DEFAULT.selectedExecutionOptions.add(DO_INCLUDE_FILE_HEADER);
		DEFAULT.selectedExecutionOptions.add(DO_INCLUDE_PROJECTION_MODE_IN_YIELD_TABLE);
		DEFAULT.selectedExecutionOptions.add(DO_INCLUDE_AGE_ROWS_IN_YIELD_TABLE);
		DEFAULT.selectedExecutionOptions.add(DO_INCLUDE_YEAR_ROWS_IN_YIELD_TABLE);
		// exclude since false: DO_INCLUDE_POLYGON_RECORD_ID_IN_YIELD_TABLE
		// exclude since false: DO_SUMMARIZE_PROJECTION_BY_POLYGON
		DEFAULT.selectedExecutionOptions.add(DO_SUMMARIZE_PROJECTION_BY_LAYER);
		// exclude since false: DO_INCLUDE_SPECIES_PROJECTION
		DEFAULT.selectedExecutionOptions.add(DO_INCLUDE_PROJECTED_MOF_VOLUMES);
		// exclude since false: DO_INCLUDE_PROJECTED_MOF_BIOMASS
		// exclude since false: DO_INCLUDE_PROJECTED_CFS_BIOMASS
		DEFAULT.selectedExecutionOptions.add(DO_INCLUDE_COLUMN_HEADERS_IN_YIELD_TABLE);
		DEFAULT.selectedExecutionOptions.add(DO_ALLOW_BASAL_AREA_AND_TREES_PER_HECTARE_VALUE_SUBSTITUTION);
		// exclude since false: DO_INCLUDE_SECONDARY_SPECIES_DOMINANT_HEIGHT_IN_YIELD_TABLE

		// exclude since false: DO_ENABLE_PROGRESS_LOGGING
		// exclude since false: DO_ENABLE_ERROR_LOGGING
		// exclude since false: DO_ENABLE_DEBUG_LOGGING

		DEFAULT.selectedDebugOptions = new ArrayList<>();
		// exclude since false: selectedDebugOptions.doIncludeDebugTimestamps
		// exclude since false: selectedDebugOptions.doIncludeDebugRoutineNames
		// exclude since false: selectedDebugOptions.doIncludeDebugEntryExit
		// exclude since false: selectedDebugOptions.doIncludeDebugIndentBlocks

		DEFAULT.minAgeStart = 0;
		DEFAULT.maxAgeStart = 600;
		DEFAULT.minAgeEnd = 1;
		DEFAULT.maxAgeEnd = 1000;
		DEFAULT.minYearStart = 1400;
		DEFAULT.maxYearStart = 3250;
		DEFAULT.minYearEnd = 1400;
		DEFAULT.maxYearEnd = 3250;
		DEFAULT.minAgeIncrement = 1;
		DEFAULT.maxAgeIncrement = 350;
		DEFAULT.forceYear = null;
		DEFAULT.combineAgeYearRange = AgeYearRangeCombinationKind.INTERSECT;
		DEFAULT.progressFrequency = new ProgressFrequency().intValue(1000);
		DEFAULT.metadataToOutput = MetadataToOutputDirective.VERSION;
		DEFAULT.filters = new Filters();
		DEFAULT.utils = new ArrayList<>();
	}
}
