{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) }}
{{- $secretName := include "nats.authSecretName" . }}
{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace $secretName) | default dict }}
{{- $secretData := (get $secretObj "data") | default dict }}
{{- $existingPassword := get $secretData .Values.auth.passwordKey }}
{{- $password := .Values.auth.password | default "" }}
{{- if and (not $password) $existingPassword }}
{{- $password = $existingPassword }}
{{- else }}
{{- $password = ($password | default (randAlphaNum 32) | b64enc) }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "nats.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.auth.usernameKey }}: {{ .Values.auth.username | b64enc | quote }}
  {{ .Values.auth.passwordKey }}: {{ $password | quote }}
{{- end }}
