apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pgBackRest.repos.configuration.secretName }}
  labels: {{- include "crunchy-postgres.labels" . | nindent 4 }}
type: Opaque
stringData:
  pgbackrest-secrets.conf: |
    [global]
    repo2-s3-key={{ .Values.pgBackRest.repos.s3.key }}
    repo2-s3-key-secret={{ .Values.pgBackRest.repos.s3.secret }}
