apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pgBackRest.repos.configuration.secretName }}
  labels: {{- include "labels" . | nindent 4 }}
type: Opaque
data:
  repo2-s3-key: {{ .Values.pgBackRest.repos.s3.key | b64enc | quote }}
  repo2-s3-key-secret: {{ .Values.pgBackRest.repos.s3.secret | b64enc | quote }}
