/* ---------------------------------------------------- */
/*  Generated by Peter Minter	                        */
/*  Created On : 08-Dec-2025 12:46 PM   				*/
/*  DBMS       : PostgreSQL 		    				*/
/* ---------------------------------------------------- */

/* ALTER TABLE rename columns */

ALTER TABLE "app-vdyp"."projection"
RENAME COLUMN "description" TO "report_description"    -- Description is a short description of the projection to help differentiate.
;


/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON COLUMN "app-vdyp"."projection"."report_title"
	IS 'Report Title is the title applied to the final report of the projection. This is a duplication of data stored in the parameters for convenience'
;

COMMENT ON COLUMN "app-vdyp"."projection"."report_description"
	IS 'Report Description is a short description of the projection to help differentiate.'
;


