#!/bin/sh
set -e
export PGPASSWORD="${POSTGRES_PASSWORD}"
psql -U postgres <<-EOSQL
  CREATE DATABASE coms;
  CREATE USER coms WITH ENCRYPTED PASSWORD 'password';
  GRANT ALL PRIVILEGES ON DATABASE coms TO coms;
EOSQL

psql -v ON_ERROR_STOP=1 -U postgres -d coms <<-EOSQL
  GRANT USAGE, CREATE ON SCHEMA public TO coms;
  ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT ALL ON TABLES TO coms;
EOSQL

psql -U postgres <<-EOSQL
  CREATE DATABASE vdyp;
  CREATE USER "app-vdyp" WITH ENCRYPTED PASSWORD 'password';
  GRANT ALL PRIVILEGES ON DATABASE vdyp TO "app-vdyp";
  CREATE USER "proxy-vdyp-rest" WITH ENCRYPTED PASSWORD 'password';
EOSQL

psql -v ON_ERROR_STOP=1 -U postgres -d vdyp <<-EOSQL
  CREATE SCHEMA "app-vdyp";
  GRANT USAGE, CREATE ON SCHEMA "app-vdyp" TO "app-vdyp";
  ALTER DEFAULT PRIVILEGES IN SCHEMA "app-vdyp"
    GRANT ALL ON TABLES TO "app-vdyp";
EOSQL
psql -U postgres <<-EOSQL
  CREATE DATABASE batch;
  CREATE USER batch WITH ENCRYPTED PASSWORD 'password';
  GRANT ALL PRIVILEGES ON DATABASE batch TO batch;
EOSQL

psql -v ON_ERROR_STOP=1 -U postgres -d batch <<-EOSQL
  CREATE SCHEMA batch;
  GRANT USAGE, CREATE ON SCHEMA batch TO batch;
  ALTER DEFAULT PRIVILEGES IN SCHEMA batch
    GRANT ALL ON TABLES TO batch;
EOSQL
