kind: GatewayService
name: vdyp-ui-dev
tags: [ns.gw-ae880]
host: vdyp-ui-dev.c50504-dev.svc
port: 80
protocol: http
routes:
  - name: vdyp-ui-dev
    tags: [ns.gw-ae880]
    hosts:
      - vdyp-ui-dev.dev.api.gov.bc.ca
