kind: DraftDataset
name: vdyp-ui-dev-dataset
title: vdyp-ui-dev-backend
organization: ministry-of-citizens-services
organizationUnit: databc
notes: |
  The vdyp-ui-dev API grants access to the /hcsv endpoint

  The endpoints in this API are accessible without authentication.

  Use the following URLs to access this API:
  - Development environment: https://vdyp-ui-dev.dev.api.gov.bc.ca
tags: [vdyp-ui-dev, openapi]
license_title: Access Only
security_class: PUBLIC
record_publish_date: '2024-01-01'
---
kind: Product
name: vdyp-ui-dev API
dataset: vdyp-ui-dev-dataset
environments:
  - name: dev
    active: false
    approval: false
    flow: public
    services: [vdyp-ui-dev]
