import * as CONSTANTS from '@/constants/constants'

export const DEFAULT_VALUES = Object.freeze({
  DERIVED_BY: CONSTANTS.DERIVED_BY.VOLUME,
  BEC_ZONE: 'IDF',
  SITE_SPECIES_VALUES: CONSTANTS.SITE_SPECIES_VALUES.SUPPLIED,
  PERCENT_STOCKABLE_AREA: 55,
  SELECTED_AGE_YEAR_RANGE: CONSTANTS.AGE_YEAR_RANGE.AGE,
  STARTING_AGE: 0,
  FINISHING_AGE: 250,
  AGE_INCREMENT: 25,
  START_YEAR: 1940,
  END_YEAR: 2040,
  YEAR_INCREMENT: 10,
  FORWARD_BACKWARD_GROW: [
    CONSTANTS.FORWARD_BACKWARD_GROW.FORWARD,
    CONSTANTS.FORWARD_BACKWARD_GROW.BACKWARD,
  ],
  VOLUME_REPORTED: [CONSTANTS.VOLUME_REPORTED.WHOLE_STEM],
  PROJECTION_TYPE: CONSTANTS.PROJECTION_TYPE.VOLUME,
  REPORT_TITLE: 'A Sample Report Title',
  MODEL_SELECTION: CONSTANTS.MODEL_SELECTION.FILE_UPLOAD,
})
