/*
 * Variable Density Yield Projection
 * API for the Variable Density Yield Projection service
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package ca.bc.gov.nrs.vdyp.ecore.utils;

/**
 * ParameterNames
 */
public class ParameterNames {
	public static final String TRIAL_RUN = "trialRun";
	public static final String PROJECTION_PARAMETERS = "Projection Parameters";
	public static final String MODEL_PARAMETERS = "Model Parameters";
	public static final String HCSV_POLYGON_INPUT_DATA = "HCSV-Polygon";
	public static final String HCSV_LAYERS_INPUT_DATA = "HCSV-Layers";
	public static final String SCSV_POLYGON_INPUT_DATA = "SCSV-Polygon";
	public static final String SCSV_LAYERS_INPUT_DATA = "SCSV-Layers";
	public static final String SCSV_HISTORY_INPUT_DATA = "SCSV-History";
	public static final String SCSV_NON_VEGETATION_INPUT_DATA = "SCSV-Non-vegetation";
	public static final String SCSV_OTHER_VEGETATION_INPUT_DATA = "SCSV-Other-vegetation";
	public static final String SCSV_POLYGON_ID_INPUT_DATA = "SCSV-PolygonId";
	public static final String SCSV_SPECIES_INPUT_DATA = "SCSV-Species";
	public static final String SCSV_VRI_ADJUST_INPUT_DATA = "SCSV-VRIAdjust";
	public static final String DCSV_INPUT_DATA = "DCSV";
	public static final String ICSV_INPUT_DATA = "ICSV";
}
