/*
 * Variable Density Yield Projection
 * API for the Variable Density Yield Projection service
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package ca.bc.gov.nrs.vdyp.backend.model.v1;

import java.io.Serializable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import io.quarkus.runtime.annotations.RegisterForReflection;

/**
 * provides details about one parameter
 */

@JsonPropertyOrder(
	{ ParameterDetailsMessage.JSON_PROPERTY_FIELD, ParameterDetailsMessage.JSON_PROPERTY_SHORT_DESCRIPTION,
			ParameterDetailsMessage.JSON_PROPERTY_PARAMETER_VALUE,
			ParameterDetailsMessage.JSON_PROPERTY_LONG_DESCRIPTION,
			ParameterDetailsMessage.JSON_PROPERTY_DEFAULT_VALUE }
)
@RegisterForReflection
public class ParameterDetailsMessage implements Serializable {

	private static final long serialVersionUID = -4514646435523721853L;

	public static final String JSON_PROPERTY_FIELD = "field";
	@JsonProperty(JSON_PROPERTY_FIELD)
	private String field;

	public static final String JSON_PROPERTY_SHORT_DESCRIPTION = "shortDescription";
	@JsonProperty(JSON_PROPERTY_SHORT_DESCRIPTION)
	private String shortDescription;

	public static final String JSON_PROPERTY_PARAMETER_VALUE = "parameterValue";
	@JsonProperty(JSON_PROPERTY_PARAMETER_VALUE)
	private String parameterValue;

	public static final String JSON_PROPERTY_LONG_DESCRIPTION = "longDescription";
	@JsonProperty(JSON_PROPERTY_LONG_DESCRIPTION)
	private String longDescription;

	public static final String JSON_PROPERTY_DEFAULT_VALUE = "defaultValue";
	@JsonProperty(JSON_PROPERTY_DEFAULT_VALUE)
	private String defaultValue;

	/**
	 * the parameter name
	 *
	 * @return field
	 **/
	@JsonProperty(value = "field")

	public String getField() {
		return field;
	}

	/**
	 * a brief description of the parameter's purpose
	 *
	 * @return shortDescription
	 **/
	@JsonProperty(value = "shortDescription")

	public String getShortDescription() {
		return shortDescription;
	}

	/**
	 * if the parameter has a value, a description of the value
	 *
	 * @return parameterValue
	 **/
	@JsonProperty(value = "parameterValue")

	public String getParameterValue() {
		return parameterValue;
	}

	/**
	 * a description of the parameter
	 *
	 * @return longDescription
	 **/
	@JsonProperty(value = "longDescription")

	public String getLongDescription() {
		return longDescription;
	}

	/**
	 * the default value used if the parameter is not specified
	 *
	 * @return defaultValue
	 **/
	@JsonProperty(value = "defaultValue")

	public String getDefaultValue() {
		return defaultValue;
	}

	public static class Builder {
		private ParameterDetailsMessage m = new ParameterDetailsMessage();

		public Builder field(String field) {
			m.field = field;
			return this;
		}

		public Builder shortDescription(String shortDescription) {
			m.shortDescription = shortDescription;
			return this;
		}

		public Builder parameterValue(String parameterValue) {
			m.parameterValue = parameterValue;
			return this;
		}

		public Builder longDescription(String longDescription) {
			m.longDescription = longDescription;
			return this;
		}

		public Builder defaultValue(String defaultValue) {
			m.defaultValue = defaultValue;
			return this;
		}

		public ParameterDetailsMessage build() {
			if (m.field == null) {
				throw new IllegalStateException("field is a required field of ParameterDetailsMessage");
			}
			if (m.shortDescription == null) {
				throw new IllegalStateException("shortDescription is a required field of ParameterDetailsMessage");
			}
			if (m.longDescription == null) {
				throw new IllegalStateException("longDescription is a required field of ParameterDetailsMessage");
			}
			if (m.defaultValue == null) {
				throw new IllegalStateException("defaultValue is a required field of ParameterDetailsMessage");
			}

			return m;
		}
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		ParameterDetailsMessage parameterDetailsMessage = (ParameterDetailsMessage) o;
		return Objects.equals(this.field, parameterDetailsMessage.field)
				&& Objects.equals(this.shortDescription, parameterDetailsMessage.shortDescription)
				&& Objects.equals(this.parameterValue, parameterDetailsMessage.parameterValue)
				&& Objects.equals(this.longDescription, parameterDetailsMessage.longDescription)
				&& Objects.equals(this.defaultValue, parameterDetailsMessage.defaultValue);
	}

	@Override
	public int hashCode() {
		return Objects.hash(field, shortDescription, parameterValue, longDescription, defaultValue);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class ParameterDetailsMessage {\n");

		sb.append("    field: ").append(toIndentedString(field)).append("\n");
		sb.append("    shortDescription: ").append(toIndentedString(shortDescription)).append("\n");
		sb.append("    parameterValue: ").append(toIndentedString(parameterValue)).append("\n");
		sb.append("    longDescription: ").append(toIndentedString(longDescription)).append("\n");
		sb.append("    defaultValue: ").append(toIndentedString(defaultValue)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}
}
