/*
 * Variable Density Yield Projection
 * API for the Variable Density Yield Projection service
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package ca.bc.gov.nrs.vdyp.backend.model.v1;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import io.quarkus.runtime.annotations.RegisterForReflection;

/**
 * This class records a utilization class for a given sp0 (species group) name.
 */
@JsonPropertyOrder(
	{ UtilizationParameter.JSON_PROPERTY_SPECIES_NAME, UtilizationParameter.JSON_PROPERTY_UTILIZATION_CLASS }
)
@RegisterForReflection
public class UtilizationParameter {
	public static final String JSON_PROPERTY_SPECIES_NAME = "speciesName";
	@JsonProperty(JSON_PROPERTY_SPECIES_NAME)
	private String speciesName;

	public static final String JSON_PROPERTY_UTILIZATION_CLASS = "utilizationClass";
	@JsonProperty(JSON_PROPERTY_UTILIZATION_CLASS)
	private String utilizationClass;

	/**
	 * Get speciesName
	 *
	 * @return speciesName
	 **/
	@JsonProperty(value = JSON_PROPERTY_SPECIES_NAME)
	public String getSpeciesName() {
		return speciesName;
	}

	public UtilizationParameter speciesName(String speciesName) {
		setSpeciesName(speciesName);
		return this;
	}

	public void setSpeciesName(String speciesName) {
		this.speciesName = speciesName;
	}

	/**
	 * Get value
	 *
	 * @return value
	 **/
	@JsonProperty(value = JSON_PROPERTY_UTILIZATION_CLASS)
	public String getUtilizationClass() {
		return utilizationClass;
	}

	public UtilizationParameter utilizationClass(String utilizationClassText) {
		setUtilizationClass(utilizationClassText);
		return this;
	}

	public void setUtilizationClass(String utilizationClassText) {
		this.utilizationClass = utilizationClassText;
	}

	public UtilizationParameter utilizationClass(UtilizationClassSet uc) {
		setUtilizationClass(uc);
		return this;
	}

	public void setUtilizationClass(UtilizationClassSet uc) {
		this.utilizationClass = uc.getValue();
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		UtilizationParameter up = (UtilizationParameter) o;
		return Objects.equals(this.speciesName, up.speciesName)
				&& Objects.equals(this.utilizationClass, up.utilizationClass);
	}

	@Override
	public int hashCode() {
		return Objects.hash(speciesName, utilizationClass);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class ");
		sb.append(UtilizationParameter.class.getSimpleName());
		sb.append(" {\n    speciesName: ").append(toIndentedString(speciesName)).append("\n");
		sb.append("    utilizationClass: ").append(toIndentedString(utilizationClass)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}
}
