/*
 * Variable Density Yield Projection
 * API for the Variable Density Yield Projection service
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package ca.bc.gov.nrs.vdyp.ecore.model.v1;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Message severity codes
 */
public enum MessageSeverityCode {

	INFORMATION("INFO"),

	STATUS("STAT"),

	WARNING("WARN"),

	ERROR("ERR"),

	FATAL_ERROR("FATAL");

	private String text;

	MessageSeverityCode(String text) {
		this.text = text;
	}

	@JsonValue
	public String getText() {
		return text;
	}

	@Override
	public String toString() {
		return String.valueOf(text);
	}

	@JsonCreator
	public static MessageSeverityCode fromValue(String value) {
		for (MessageSeverityCode b : MessageSeverityCode.values()) {
			if (b.text.equals(value)) {
				return b;
			}
		}
		throw new IllegalArgumentException("Unexpected value '" + value + "'");
	}
}
