/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 23-Oct-2025 9:36:17 AM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "app-vdyp"."projection_param_preset" CASCADE
;

/* Create Tables */

CREATE TABLE "app-vdyp"."projection_param_preset"
(
	"projection_param_preset_guid" UUID NOT NULL,    -- projection_param_preset_guid is a unique identifier for the record.
	"vdyp_user_guid" UUID NOT NULL,    -- vdyp_user_guid: Is a foreign key to vdyp_user: VDYP User is used to track profiles for users that access the VDYP system and control access to Projection files, parameters and results
	"preset_name" varchar(100) NOT NULL,    -- Preset Name is a short description of the presets for user reference
	"projection_parameters_json" varchar(2000) NOT NULL,    -- Projection Parameters JSON is a JSON string that represents the parameters that this preset saves
	"revision_count" decimal(10) NOT NULL   DEFAULT 0,    -- REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.
	"create_user" varchar(64) NOT NULL,    -- CREATE_USER is an audit column that indicates the user that created the record.
	"create_date" DATE NOT NULL   DEFAULT CURRENT_TIMESTAMP,    -- CREATE_DATE is the date and time the row of data was created.
	"update_user" varchar(64) NOT NULL,    -- UPDATE_USER is an audit column that indicates the user that updated the record.
	"update_date" DATE NOT NULL   DEFAULT CURRENT_TIMESTAMP    -- UPDATE_DATE is the date and time the row of data was updated.
)
TABLESPACE	PG_DEFAULT
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "app-vdyp"."projection_param_preset" ADD CONSTRAINT "prjprmpr_pk"
	PRIMARY KEY ("projection_param_preset_guid")
;

ALTER TABLE "app-vdyp"."projection_param_preset" ADD CONSTRAINT "prjprmpr_uk" UNIQUE ("vdyp_user_guid")
;

CREATE INDEX "prjprmpr_user_idx" ON "app-vdyp"."projection_param_preset" ("vdyp_user_guid" ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE "app-vdyp"."projection_param_preset" ADD CONSTRAINT "prjprmpr_user_fk"
	FOREIGN KEY ("vdyp_user_guid") REFERENCES "app-vdyp"."vdyp_user" ("vdyp_user_guid") ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "app-vdyp"."projection_param_preset"
	IS 'Projection Parameter Preset is a named saved copy of the JSON Parameters to run a projection.'
;

COMMENT ON COLUMN "app-vdyp"."projection_param_preset"."projection_param_preset_guid"
	IS 'projection_param_preset_guid is a unique identifier for the record.'
;

COMMENT ON COLUMN "app-vdyp"."projection_param_preset"."vdyp_user_guid"
	IS 'vdyp_user_guid: Is a foreign key to vdyp_user: VDYP User is used to track profiles for users that access the VDYP system and control access to Projection files, parameters and results'
;

COMMENT ON COLUMN "app-vdyp"."projection_param_preset"."preset_name"
	IS 'Preset Name is a short description of the presets for user reference'
;

COMMENT ON COLUMN "app-vdyp"."projection_param_preset"."projection_parameters_json"
	IS 'Projection Parameters JSON is a JSON string that represents the parameters that this preset saves'
;

COMMENT ON COLUMN "app-vdyp"."projection_param_preset"."revision_count"
	IS 'REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.'
;

COMMENT ON COLUMN "app-vdyp"."projection_param_preset"."create_user"
	IS 'CREATE_USER is an audit column that indicates the user that created the record.'
;

COMMENT ON COLUMN "app-vdyp"."projection_param_preset"."create_date"
	IS 'CREATE_DATE is the date and time the row of data was created.'
;

COMMENT ON COLUMN "app-vdyp"."projection_param_preset"."update_user"
	IS 'UPDATE_USER is an audit column that indicates the user that updated the record.'
;

COMMENT ON COLUMN "app-vdyp"."projection_param_preset"."update_date"
	IS 'UPDATE_DATE is the date and time the row of data was updated.'
;