/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 25-Sep-2025 10:36:14 AM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "app-vdyp"."projection" CASCADE
;

/* Create Tables */

CREATE TABLE "app-vdyp"."projection"
(
	"projection_guid" UUID NOT NULL,    -- projection_guid is a unique identifier for the record.
	"layer_projection_file_set_guid" UUID NOT NULL,    -- LAYER_projection_file_set_guid: Is a foreign key to projection_file_set: Projection File Set is a typed grouping of Files that can be used in a projection. This will handle groups of Polygon files, groups of Layer files and groups of Result files.
	"polygon_projection_file_set_guid" UUID NOT NULL,    -- POLYGON_projection_file_set_guid: Is a foreign key to projection_file_set: Projection File Set is a typed grouping of Files that can be used in a projection. This will handle groups of Polygon files, groups of Layer files and groups of Result files.
	"calculation_engine_code" varchar(10) NOT NULL,    -- calculation_engine_code: Is a foreign key to calculation_engine_code: Calculation Engine Code is a future proofing aggregation of versions of individual internal components Values are: - 8.0 
	"vdyp_user_guid" UUID NOT NULL,    -- vdyp_user_guid: Is a foreign key to vdyp_user: VDYP User is used to track profiles for users that access the VDYP system and control access to Projection files, parameters and results
	"projection_status_code" varchar(10) NOT NULL,    -- projection_status_code: Is a foreign key to projection_status_code: Projection Status Code is the current status of the projection. Values are: - Draft - Queued - Started - Completed - Canceled
	"result_projection_file_set_guid" UUID NOT NULL,    -- RESULT_projection_file_set_guid: Is a foreign key to projection_file_set: Projection File Set is a typed grouping of Files that can be used in a projection. This will handle groups of Polygon files, groups of Layer files and groups of Result files.
	"projection_parameters_json" varchar(1000) NOT NULL,    -- Projection Parameters JSON is a JSON encoded string containing all parameters required to run this projection
	"start_date" TIMESTAMP NULL,    -- Start Date is the date the projection processing was started
	"end_date" TIMESTAMP NULL,    -- End date is the date the projection completed processing
	"revision_count" decimal(10) NOT NULL   DEFAULT 0,    -- REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.
	"create_user" varchar(64) NOT NULL,    -- CREATE_USER is an audit column that indicates the user that created the record.
	"create_date" DATE NOT NULL   DEFAULT CURRENT_TIMESTAMP,    -- CREATE_DATE is the date and time the row of data was created.
	"update_user" varchar(64) NOT NULL,    -- UPDATE_USER is an audit column that indicates the user that updated the record.
	"update_date" DATE NOT NULL   DEFAULT CURRENT_TIMESTAMP    -- UPDATE_DATE is the date and time the row of data was updated.
)
TABLESPACE	PG_DEFAULT
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "app-vdyp"."projection" ADD CONSTRAINT "prjctn_pk"
	PRIMARY KEY ("projection_guid")
;

CREATE INDEX "prjctn_fileset_layer_idx" ON "app-vdyp"."projection" ("layer_projection_file_set_guid" ASC)
;

CREATE INDEX "prjctn_fileset_polygon_idx" ON "app-vdyp"."projection" ("polygon_projection_file_set_guid" ASC)
;

CREATE INDEX "prjctn_calc_eng_idx" ON "app-vdyp"."projection" ("calculation_engine_code" ASC)
;

CREATE INDEX "prjctn_user_idx" ON "app-vdyp"."projection" ("vdyp_user_guid" ASC)
;

CREATE INDEX "prjctn_prjstat_idx" ON "app-vdyp"."projection" ("projection_status_code" ASC)
;

CREATE INDEX "prjctn_fileset_result_idx" ON "app-vdyp"."projection" ("result_projection_file_set_guid" ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE "app-vdyp"."projection" ADD CONSTRAINT "prjctn_fileset_layer_fk"
	FOREIGN KEY () REFERENCES  () ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "app-vdyp"."projection" ADD CONSTRAINT "prjctn_fileset_polygon_fk"
	FOREIGN KEY () REFERENCES  () ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "app-vdyp"."projection" ADD CONSTRAINT "prjctn_calc_eng_fk"
	FOREIGN KEY ("calculation_engine_code") REFERENCES "app-vdyp"."calculation_engine_code" ("calculation_engine_code") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "app-vdyp"."projection" ADD CONSTRAINT "prjctn_user_fk"
	FOREIGN KEY () REFERENCES  () ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "app-vdyp"."projection" ADD CONSTRAINT "prjctn_prjstat_fk"
	FOREIGN KEY ("projection_status_code") REFERENCES "app-vdyp"."projection_status_code" ("projection_status_code") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "app-vdyp"."projection" ADD CONSTRAINT "prjctn_fileset_result_fk"
	FOREIGN KEY () REFERENCES  () ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "app-vdyp"."projection"
	IS 'Projection is a collection of all the inputs used to create a VDYP projection including, a Polygon File Set, a Layer File Set, and a JSON encoded string of parameters '
;

COMMENT ON COLUMN "app-vdyp"."projection"."projection_guid"
	IS 'projection_guid is a unique identifier for the record.'
;

COMMENT ON COLUMN "app-vdyp"."projection"."layer_projection_file_set_guid"
	IS 'LAYER_projection_file_set_guid: Is a foreign key to projection_file_set: Projection File Set is a typed grouping of Files that can be used in a projection. This will handle groups of Polygon files, groups of Layer files and groups of Result files.'
;

COMMENT ON COLUMN "app-vdyp"."projection"."polygon_projection_file_set_guid"
	IS 'POLYGON_projection_file_set_guid: Is a foreign key to projection_file_set: Projection File Set is a typed grouping of Files that can be used in a projection. This will handle groups of Polygon files, groups of Layer files and groups of Result files.'
;

COMMENT ON COLUMN "app-vdyp"."projection"."calculation_engine_code"
	IS 'calculation_engine_code: Is a foreign key to calculation_engine_code: Calculation Engine Code is a future proofing aggregation of versions of individual internal components Values are: - 8.0 '
;

COMMENT ON COLUMN "app-vdyp"."projection"."vdyp_user_guid"
	IS 'vdyp_user_guid: Is a foreign key to vdyp_user: VDYP User is used to track profiles for users that access the VDYP system and control access to Projection files, parameters and results'
;

COMMENT ON COLUMN "app-vdyp"."projection"."projection_status_code"
	IS 'projection_status_code: Is a foreign key to projection_status_code: Projection Status Code is the current status of the projection. Values are: - Draft - Queued - Started - Completed - Canceled'
;

COMMENT ON COLUMN "app-vdyp"."projection"."result_projection_file_set_guid"
	IS 'RESULT_projection_file_set_guid: Is a foreign key to projection_file_set: Projection File Set is a typed grouping of Files that can be used in a projection. This will handle groups of Polygon files, groups of Layer files and groups of Result files.'
;

COMMENT ON COLUMN "app-vdyp"."projection"."projection_parameters_json"
	IS 'Projection Parameters JSON is a JSON encoded string containing all parameters required to run this projection'
;

COMMENT ON COLUMN "app-vdyp"."projection"."start_date"
	IS 'Start Date is the date the projection processing was started'
;

COMMENT ON COLUMN "app-vdyp"."projection"."end_date"
	IS 'End date is the date the projection completed processing'
;

COMMENT ON COLUMN "app-vdyp"."projection"."revision_count"
	IS 'REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.'
;

COMMENT ON COLUMN "app-vdyp"."projection"."create_user"
	IS 'CREATE_USER is an audit column that indicates the user that created the record.'
;

COMMENT ON COLUMN "app-vdyp"."projection"."create_date"
	IS 'CREATE_DATE is the date and time the row of data was created.'
;

COMMENT ON COLUMN "app-vdyp"."projection"."update_user"
	IS 'UPDATE_USER is an audit column that indicates the user that updated the record.'
;

COMMENT ON COLUMN "app-vdyp"."projection"."update_date"
	IS 'UPDATE_DATE is the date and time the row of data was updated.'
;