/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 15-Oct-2025 9:18:38 AM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "app-vdyp"."projection_batch_mapping" CASCADE
;

/* Create Tables */

CREATE TABLE "app-vdyp"."projection_batch_mapping"
(
	"projection_batch_mapping_guid" UUID NOT NULL,    -- projection_batch_mapping_guid is a unique identifier for the record.
	"batch_job_guid" UUID NOT NULL,    -- batch_job_guid: Is a foreign key to batch_job: Batch Job is a projections entry in the Batch Job System
	"projection_guid" UUID NOT NULL,    -- projection_guid: Is a foreign key to projection: Projection is a collection of all the inputs used to create a VDYP projection including, a Polygon File Set, a Layer File Set, and a JSON encoded string of parameters 
	"partition_count" INT NOT NULL,    -- Partition Count is the number of partitions that the batch job has created for the mapped projection
	"completed_partition_count" INT NOT NULL,    -- Completed Partition Count is the number of partitions the batch system is reporting as completed 
	"error_count" INT NOT NULL,    -- Error Count is the number of errors reported during processing
	"warning_count" INT NOT NULL,    -- Warning Count is the number of warnings reported during processing
	"revision_count" decimal(10) NOT NULL   DEFAULT 0,    -- REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.
	"create_user" varchar(64) NOT NULL,    -- CREATE_USER is an audit column that indicates the user that created the record.
	"create_date" DATE NOT NULL   DEFAULT CURRENT_TIMESTAMP,    -- CREATE_DATE is the date and time the row of data was created.
	"update_user" varchar(64) NOT NULL,    -- UPDATE_USER is an audit column that indicates the user that updated the record.
	"update_date" DATE NOT NULL   DEFAULT CURRENT_TIMESTAMP    -- UPDATE_DATE is the date and time the row of data was updated.
)
TABLESPACE	PG_DEFAULT
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "app-vdyp"."projection_batch_mapping" ADD CONSTRAINT "prjbatmap_pk"
	PRIMARY KEY ("projection_batch_mapping_guid")
;

ALTER TABLE "app-vdyp"."projection_batch_mapping" ADD CONSTRAINT "prjbatmap_uk" UNIQUE ("batch_job_guid","projection_guid")
;

CREATE INDEX "prjbatmap_batch_jo_idx" ON "app-vdyp"."projection_batch_mapping" ("batch_job_guid" ASC)
;

CREATE INDEX "prjbatmap_prjctn_idx" ON "app-vdyp"."projection_batch_mapping" ("projection_guid" ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE "app-vdyp"."projection_batch_mapping" ADD CONSTRAINT "prjbatmap_prjctn_fk"
	FOREIGN KEY ("projection_guid") REFERENCES "app-vdyp"."projection" ("projection_guid") ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "app-vdyp"."projection_batch_mapping"
	IS 'Projection Batch Mapping is a mapping of internal projections to external batch system GUID along with details that are only updated by the batch system'
;

COMMENT ON COLUMN "app-vdyp"."projection_batch_mapping"."projection_batch_mapping_guid"
	IS 'projection_batch_mapping_guid is a unique identifier for the record.'
;

COMMENT ON COLUMN "app-vdyp"."projection_batch_mapping"."batch_job_guid"
	IS 'batch_job_guid: Is a foreign key to batch_job: Batch Job is a projections entry in the Batch Job System'
;

COMMENT ON COLUMN "app-vdyp"."projection_batch_mapping"."projection_guid"
	IS 'projection_guid: Is a foreign key to projection: Projection is a collection of all the inputs used to create a VDYP projection including, a Polygon File Set, a Layer File Set, and a JSON encoded string of parameters '
;

COMMENT ON COLUMN "app-vdyp"."projection_batch_mapping"."partition_count"
	IS 'Partition Count is the number of partitions that the batch job has created for the mapped projection'
;

COMMENT ON COLUMN "app-vdyp"."projection_batch_mapping"."completed_partition_count"
	IS 'Completed Partition Count is the number of partitions the batch system is reporting as completed '
;

COMMENT ON COLUMN "app-vdyp"."projection_batch_mapping"."error_count"
	IS 'Error Count is the number of errors reported during processing'
;

COMMENT ON COLUMN "app-vdyp"."projection_batch_mapping"."warning_count"
	IS 'Warning Count is the number of warnings reported during processing'
;

COMMENT ON COLUMN "app-vdyp"."projection_batch_mapping"."revision_count"
	IS 'REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.'
;

COMMENT ON COLUMN "app-vdyp"."projection_batch_mapping"."create_user"
	IS 'CREATE_USER is an audit column that indicates the user that created the record.'
;

COMMENT ON COLUMN "app-vdyp"."projection_batch_mapping"."create_date"
	IS 'CREATE_DATE is the date and time the row of data was created.'
;

COMMENT ON COLUMN "app-vdyp"."projection_batch_mapping"."update_user"
	IS 'UPDATE_USER is an audit column that indicates the user that updated the record.'
;

COMMENT ON COLUMN "app-vdyp"."projection_batch_mapping"."update_date"
	IS 'UPDATE_DATE is the date and time the row of data was updated.'
;