/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 23-Oct-2025 9:36:17 AM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "app-vdyp"."file_mapping" CASCADE
;

/* Create Tables */

CREATE TABLE "app-vdyp"."file_mapping"
(
	"file_mapping_guid" UUID NOT NULL,    -- file_mapping_guid is a unique identifier for the record.
	"coms_object_guid" UUID NOT NULL,    -- coms_object_guid: Is a foreign key to coms_object: Object is an Object in the COMS microservice.
	"projection_file_set_guid" UUID NOT NULL,    -- projection_file_set_guid: Is a foreign key to projection_file_set: Projection File Set is a typed grouping of Files that can be used in a projection. This will handle groups of Polygon files, groups of Layer files and groups of Result files.
	"revision_count" decimal(10) NOT NULL   DEFAULT 0,    -- REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.
	"create_user" varchar(64) NOT NULL,    -- CREATE_USER is an audit column that indicates the user that created the record.
	"create_date" DATE NOT NULL   DEFAULT CURRENT_TIMESTAMP,    -- CREATE_DATE is the date and time the row of data was created.
	"update_user" varchar(64) NOT NULL,    -- UPDATE_USER is an audit column that indicates the user that updated the record.
	"update_date" DATE NOT NULL   DEFAULT CURRENT_TIMESTAMP    -- UPDATE_DATE is the date and time the row of data was updated.
)
TABLESPACE	PG_DEFAULT
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "app-vdyp"."file_mapping" ADD CONSTRAINT "filemap_pk"
	PRIMARY KEY ("file_mapping_guid")
;

ALTER TABLE "app-vdyp"."file_mapping" ADD CONSTRAINT "filemap_uk" UNIQUE ("coms_object_guid","projection_file_set_guid")
;

CREATE INDEX "filemap_coms_obj_idx" ON "app-vdyp"."file_mapping" ("coms_object_guid" ASC)
;

CREATE INDEX "filemap_fileset_idx" ON "app-vdyp"."file_mapping" ("projection_file_set_guid" ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE "app-vdyp"."file_mapping" ADD CONSTRAINT "filemap_fileset_fk"
	FOREIGN KEY ("projection_file_set_guid") REFERENCES "app-vdyp"."projection_file_set" ("projection_file_set_guid") ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "app-vdyp"."file_mapping"
	IS 'File is a mapping of an object in the COMS system to a File Set in VDYP'
;

COMMENT ON COLUMN "app-vdyp"."file_mapping"."file_mapping_guid"
	IS 'file_mapping_guid is a unique identifier for the record.'
;

COMMENT ON COLUMN "app-vdyp"."file_mapping"."coms_object_guid"
	IS 'coms_object_guid: Is a foreign key to coms_object: Object is an Object in the COMS microservice.'
;

COMMENT ON COLUMN "app-vdyp"."file_mapping"."projection_file_set_guid"
	IS 'projection_file_set_guid: Is a foreign key to projection_file_set: Projection File Set is a typed grouping of Files that can be used in a projection. This will handle groups of Polygon files, groups of Layer files and groups of Result files.'
;

COMMENT ON COLUMN "app-vdyp"."file_mapping"."revision_count"
	IS 'REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.'
;

COMMENT ON COLUMN "app-vdyp"."file_mapping"."create_user"
	IS 'CREATE_USER is an audit column that indicates the user that created the record.'
;

COMMENT ON COLUMN "app-vdyp"."file_mapping"."create_date"
	IS 'CREATE_DATE is the date and time the row of data was created.'
;

COMMENT ON COLUMN "app-vdyp"."file_mapping"."update_user"
	IS 'UPDATE_USER is an audit column that indicates the user that updated the record.'
;

COMMENT ON COLUMN "app-vdyp"."file_mapping"."update_date"
	IS 'UPDATE_DATE is the date and time the row of data was updated.'
;