/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 25-Sep-2025 10:36:14 AM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "app-vdyp"."projection_file_set" CASCADE
;

/* Create Tables */

CREATE TABLE "app-vdyp"."projection_file_set"
(
	"projection_file_set_guid" UUID NOT NULL,    -- projection_file_set_guid is a unique identifier for the record.
	"vdyp_user_guid" UUID NOT NULL,    -- vdyp_user_guid: Is a foreign key to vdyp_user: VDYP User is used to track profiles for users that access the VDYP system and control access to Projection files, parameters and results
	"file_set_type_code" varchar(10) NOT NULL,    -- file_set_type_code: Is a foreign key to file_set_type_code: File Set Type Code is the mode that the file set will be used. Values are: - Polygon - Layer - Result
	"file_set_name" varchar(4000) NULL,    -- File Set Name is a short description of the files contained in the set
	"description" varchar(4000) NULL,    -- Description is a long description of the files contained in the set
	"revision_count" decimal(10) NOT NULL   DEFAULT 0,    -- REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.
	"create_user" varchar(64) NOT NULL,    -- CREATE_USER is an audit column that indicates the user that created the record.
	"create_date" DATE NOT NULL   DEFAULT CURRENT_TIMESTAMP,    -- CREATE_DATE is the date and time the row of data was created.
	"update_user" varchar(64) NOT NULL,    -- UPDATE_USER is an audit column that indicates the user that updated the record.
	"update_date" DATE NOT NULL   DEFAULT CURRENT_TIMESTAMP    -- UPDATE_DATE is the date and time the row of data was updated.
)
TABLESPACE	PG_DEFAULT
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "app-vdyp"."projection_file_set" ADD CONSTRAINT "fileset_pk"
	PRIMARY KEY ("projection_file_set_guid")
;

CREATE INDEX "fileset_user_idx" ON "app-vdyp"."projection_file_set" ("vdyp_user_guid" ASC)
;

CREATE INDEX "fileset_flsttype_idx" ON "app-vdyp"."projection_file_set" ("file_set_type_code" ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE "app-vdyp"."projection_file_set" ADD CONSTRAINT "fileset_user_fk"
	FOREIGN KEY () REFERENCES  () ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "app-vdyp"."projection_file_set" ADD CONSTRAINT "fileset_flsttype_fk"
	FOREIGN KEY ("file_set_type_code") REFERENCES "app-vdyp"."file_set_type_code" ("file_set_type_code") ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "app-vdyp"."projection_file_set"
	IS 'Projection File Set is a typed grouping of Files that can be used in a projection. This will handle groups of Polygon files, groups of Layer files and groups of Result files.'
;

COMMENT ON COLUMN "app-vdyp"."projection_file_set"."projection_file_set_guid"
	IS 'projection_file_set_guid is a unique identifier for the record.'
;

COMMENT ON COLUMN "app-vdyp"."projection_file_set"."vdyp_user_guid"
	IS 'vdyp_user_guid: Is a foreign key to vdyp_user: VDYP User is used to track profiles for users that access the VDYP system and control access to Projection files, parameters and results'
;

COMMENT ON COLUMN "app-vdyp"."projection_file_set"."file_set_type_code"
	IS 'file_set_type_code: Is a foreign key to file_set_type_code: File Set Type Code is the mode that the file set will be used. Values are: - Polygon - Layer - Result'
;

COMMENT ON COLUMN "app-vdyp"."projection_file_set"."file_set_name"
	IS 'File Set Name is a short description of the files contained in the set'
;

COMMENT ON COLUMN "app-vdyp"."projection_file_set"."description"
	IS 'Description is a long description of the files contained in the set'
;

COMMENT ON COLUMN "app-vdyp"."projection_file_set"."revision_count"
	IS 'REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.'
;

COMMENT ON COLUMN "app-vdyp"."projection_file_set"."create_user"
	IS 'CREATE_USER is an audit column that indicates the user that created the record.'
;

COMMENT ON COLUMN "app-vdyp"."projection_file_set"."create_date"
	IS 'CREATE_DATE is the date and time the row of data was created.'
;

COMMENT ON COLUMN "app-vdyp"."projection_file_set"."update_user"
	IS 'UPDATE_USER is an audit column that indicates the user that updated the record.'
;

COMMENT ON COLUMN "app-vdyp"."projection_file_set"."update_date"
	IS 'UPDATE_DATE is the date and time the row of data was updated.'
;