/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 15-Oct-2025 9:18:38 AM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "app-vdyp"."vdyp_user" CASCADE
;

/* Create Tables */

CREATE TABLE "app-vdyp"."vdyp_user"
(
	"vdyp_user_guid" UUID NOT NULL,    -- vdyp_user_guid is a unique identifier for the record.
	"oidc_id" varchar(100) NOT NULL,    -- OpenID Connect ID is the Identifier for this profile that is profided from the Bc Government Single Sign On Service to identify this user as unique.
	"user_type_code" varchar(10) NOT NULL,    -- user_type_code: Is a foreign key to user_type_code: User Type Code is a code representing an access level for a user profile  Values are: - Admin - Super User - User
	"first_name" varchar(50) NOT NULL,    -- First Name is the first name of the user that this profile corresponds to
	"last_name" varchar(50) NOT NULL,    -- Last Name is the last name of the user that this profile corresponds to
	"revision_count" decimal(10) NOT NULL   DEFAULT 0,    -- REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.
	"create_user" varchar(64) NOT NULL,    -- CREATE_USER is an audit column that indicates the user that created the record.
	"create_date" DATE NOT NULL   DEFAULT CURRENT_TIMESTAMP,    -- CREATE_DATE is the date and time the row of data was created.
	"update_user" varchar(64) NOT NULL,    -- UPDATE_USER is an audit column that indicates the user that updated the record.
	"update_date" DATE NOT NULL   DEFAULT CURRENT_TIMESTAMP    -- UPDATE_DATE is the date and time the row of data was updated.
)
TABLESPACE	PG_DEFAULT
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "app-vdyp"."vdyp_user" ADD CONSTRAINT "user_pk"
	PRIMARY KEY ("vdyp_user_guid")
;

ALTER TABLE "app-vdyp"."vdyp_user" ADD CONSTRAINT "user_uk" UNIQUE ("oidc_id")
;

CREATE INDEX "user_usertype_idx" ON "app-vdyp"."vdyp_user" ("user_type_code" ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE "app-vdyp"."vdyp_user" ADD CONSTRAINT "user_usertype_fk"
	FOREIGN KEY ("user_type_code") REFERENCES "app-vdyp"."user_type_code" ("user_type_code") ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "app-vdyp"."vdyp_user"
	IS 'VDYP User is used to track profiles for users that access the VDYP system and control access to Projection files, parameters and results'
;

COMMENT ON COLUMN "app-vdyp"."vdyp_user"."vdyp_user_guid"
	IS 'vdyp_user_guid is a unique identifier for the record.'
;

COMMENT ON COLUMN "app-vdyp"."vdyp_user"."oidc_id"
	IS 'OpenID Connect ID is the Identifier for this profile that is profided from the Bc Government Single Sign On Service to identify this user as unique.'
;

COMMENT ON COLUMN "app-vdyp"."vdyp_user"."user_type_code"
	IS 'user_type_code: Is a foreign key to user_type_code: User Type Code is a code representing an access level for a user profile  Values are: - Admin - Super User - User'
;

COMMENT ON COLUMN "app-vdyp"."vdyp_user"."first_name"
	IS 'First Name is the first name of the user that this profile corresponds to'
;

COMMENT ON COLUMN "app-vdyp"."vdyp_user"."last_name"
	IS 'Last Name is the last name of the user that this profile corresponds to'
;

COMMENT ON COLUMN "app-vdyp"."vdyp_user"."revision_count"
	IS 'REVISION_COUNT is the number of times that the row of data has been changed. The column is used for optimistic locking via application code.'
;

COMMENT ON COLUMN "app-vdyp"."vdyp_user"."create_user"
	IS 'CREATE_USER is an audit column that indicates the user that created the record.'
;

COMMENT ON COLUMN "app-vdyp"."vdyp_user"."create_date"
	IS 'CREATE_DATE is the date and time the row of data was created.'
;

COMMENT ON COLUMN "app-vdyp"."vdyp_user"."update_user"
	IS 'UPDATE_USER is an audit column that indicates the user that updated the record.'
;

COMMENT ON COLUMN "app-vdyp"."vdyp_user"."update_date"
	IS 'UPDATE_DATE is the date and time the row of data was updated.'
;