{{- if and .Values.global.secrets .Values.global.secrets.enabled}}
{{- $databaseUser := .Values.global.secrets.databaseUser| default "quickstart"  }}
{{- $databasePassword := .Values.global.secrets.databasePassword | default (randAlphaNum 10) }}
{{- $COMS_DB_PASSWORD := .Values.global.secrets.COMS_DB_PASSWORD }}
{{- $VDYP_DB_PASSWORD := .Values.global.secrets.VDYP_DB_PASSWORD }}
{{- $BATCH_DB_PASSWORD := .Values.global.secrets.BATCH_DB_PASSWORD }}
{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace  .Release.Name ) | default dict }}
{{- $secretData := (get $secretObj "data") | default dict }}
  # set below to existing secret data or generate a random one when not exists
{{- $COMS_DB_PASSWORD = (get $secretData "COMS_DB_PASSWORD") | default ($COMS_DB_PASSWORD | b64enc) }}
{{- $VDYP_DB_PASSWORD = (get $secretData "VDYP_DB_PASSWORD") | default ($VDYP_DB_PASSWORD | b64enc) }}
{{- $BATCH_DB_PASSWORD = (get $secretData "$BATCH_DB_PASSWORD") | default ($BATCH_DB_PASSWORD | b64enc) }}
{{- $databasePassword = (get $secretData "databasePassword") | default ($databasePassword | b64enc) }}
{{- $databaseName := .Values.global.secrets.databaseName| default "quickstart" }}
{{- $host := printf "%s-%s:5432" .Release.Name .Values.global.databaseAlias }}
{{- $hostWithoutPort := printf "%s-%s" .Release.Name .Values.global.databaseAlias }}
{{- $databaseURL := printf "postgresql://%s:%s@%s/%s" $databaseUser (b64dec $databasePassword) $host $databaseName }}
{{- $databaseJDBCURL := printf "jdbc:postgresql://%s:%s@%s/%s" $databaseUser (b64dec $databasePassword) $host $databaseName }}
{{- $databaseJDBCURLNoCreds := printf "jdbc:postgresql://%s/%s" $host $databaseName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels: {{- include "labels" . | nindent 4 }}
  {{- if .Values.global.secrets.persist }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
type: Opaque
data:
  databasePassword: {{ $databasePassword | quote }}
  postgres-password: {{ $databasePassword  | quote }}
  password: {{ $databasePassword | quote }}
  databaseUser: {{  $databaseUser | b64enc | quote }}
  databaseName: {{  $databaseName | b64enc | quote }}
  databaseURL: {{ $databaseURL | b64enc | quote }}
  databaseJDBCURL: {{ $databaseJDBCURL | b64enc | quote }}
  databaseJDBCURLNoCreds: {{ $databaseJDBCURLNoCreds | b64enc | quote }}
  FLYWAY_URL: {{ $databaseJDBCURLNoCreds | b64enc | quote }}
  FLYWAY_USER: {{ $databaseUser | b64enc | quote }}
  FLYWAY_PASSWORD: {{ $databasePassword | quote }}
  POSTGRES_PASSWORD: {{ $databasePassword | quote }}
  POSTGRES_USER: {{ $databaseUser | b64enc | quote }}
  POSTGRES_DATABASE: {{ $databaseName | b64enc | quote }}
  COMS_DB_PASSWORD: {{ $COMS_DB_PASSWORD | quote }}
  VDYP_DB_PASSWORD: {{ $VDYP_DB_PASSWORD | quote }}
  BATCH_DB_PASSWORD: {{ $BATCH_DB_PASSWORD | quote }}

{{- end }}
