/* ---------------------------------------------------- */
/*  Generated by Peter Minter	                        */
/*  Created On : 08-Dec-2025 12:46 PM   				*/
/*  DBMS       : PostgreSQL 		    				*/
/* ---------------------------------------------------- */

/* ALTER TABLE rename columns */
ALTER TABLE "app-vdyp"."projection_batch_mapping"
RENAME COLUMN "partition_count" TO "polygon_count";

ALTER TABLE "app-vdyp"."projection_batch_mapping"
RENAME COLUMN "completed_partition_count" TO "completed_polygon_count";

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON COLUMN "app-vdyp"."projection_batch_mapping"."polygon_count"
	IS 'Polygon Count is the number of polygons that the batch job has determined exist for the mapped projection'
;

COMMENT ON COLUMN "app-vdyp"."projection_batch_mapping"."completed_polygon_count"
	IS 'Completed Polygon Count is the number of polygons the batch system is reporting as completed '
;

