/* ---------------------------------------------------- */
/*  Generated by Peter Minter	                        */
/*  Created On : 08-Dec-2025 12:46 PM   				*/
/*  DBMS       : PostgreSQL 		    				*/
/* ---------------------------------------------------- */

/* ALTER TABLE new columns */

ALTER TABLE "app-vdyp"."projection"
ADD COLUMN "report_title" varchar(250) NOT NULL    -- Report Title is the title applied to the final report of the projection. This is a duplication of data stored in the parameters for convenience
;

ALTER TABLE "app-vdyp"."projection"
ADD COLUMN "description" varchar(500) NOT NULL    -- Description is a short description of the projection to help differentiate.
;


/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON COLUMN "app-vdyp"."projection"."report_title"
	IS 'Report Title is the title applied to the final report of the projection. This is a duplication of data stored in the parameters for convenience'
;

COMMENT ON COLUMN "app-vdyp"."projection"."description"
	IS 'Description is a short description of the projection to help differentiate.'
;


