apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: "#{NAMESPACE}#"
  name: "vdyp-web-ui-deployment-#{ENV}#"
spec:
  selector:
    matchLabels:
      app: vdyp-web-ui-#{ENV}#
  replicas: 2
  template:
    metadata:
      labels:
        app: vdyp-web-ui-#{ENV}#
        project: vdyp-#{ENV}#
    spec:
      containers:
        - name: container
          image: >-
            ghcr.io/vividroyjeong/nr-vdyp-vdyp-web-ui:#{TAG}#
          ports:
            - containerPort: #{ACTIVE_PORT}#
              protocol: TCP
          env:
            - name: ACTIVE_PORT
              valueFrom:
                configMapKeyRef:
                  name: vdyp-web-ui-config-#{ENV}#
                  key: ACTIVE_PORT
            - name: LOG_LEVEL
              value: "#{LOG_LEVEL}#"
            - name: BACKEND_URL
              value: "#{BACKEND_URL}#"
          securityContext:
            capabilities:
              add:
                - NET_BIND_SERVICE              
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 200m
              memory: 400Mi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
