name: PR

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'frontend/**'
      - 'backend/**'
      - 'migrations/**'

concurrency:
  # Cancel if re-attempted
  group: ${{ github.event_name }}
  cancel-in-progress: true

jobs:
  # https://github.com/bcgov-nr/action-builder-ghcr
  builds:
    name: Builds
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        package: [backend, frontend, migrations]
    timeout-minutes: 10
    steps:
      - id: trimBranchName
        name: trim branch name if necessary
        run: |
          export branchTag="${{ github.ref_name }}"
          trimTag="${branchTag##*/}"
          echo "BRANCH_TAG=$trimTag" >> $GITHUB_OUTPUT
    
      - uses: bcgov-nr/action-builder-ghcr@v2.0.2
        with:
          build_context: ${{ matrix.build_context }}
          keep_versions: 10
          package: ${{ matrix.package }}
          tag: ${{ steps.trimBranchName.outputs.BRANCH_TAG }}
          tag_fallback: latest
          triggers: ('${{ matrix.package }}/')

  # https://github.com/bcgov/quickstart-openshift-helpers
  deploys:
    name: Deploys
    needs: [builds]
    uses: bcgov/quickstart-openshift-helpers/.github/workflows/.deployer.yml@v0.4.1
    secrets:
      oc_namespace: ${{ secrets.OC_NAMESPACE }}
      oc_token: ${{ secrets.OC_TOKEN }}
    with:
      triggers: ('backend/' 'frontend/' 'migrations/')
      params:
        --set global.secrets.persist=false

  # tests:
  #   name: Tests
  #   if: needs.deploys.outputs.triggered == 'true'
  #   needs: [deploys]
  #   uses: ./.github/workflows/.tests.yml
  #   with:
  #     target: ${{ github.event.number }}

  results:
    name: PR Results
    needs: [builds, deploys]
    if: always() && (!failure()) && (!cancelled())
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Success!"
