permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:
    inputs:
      BUILD_TARGET:
        type: choice
        description: 'Name of project to build'
        options:
          - vdyp-web-ui
        required: true
      TAG:
        required: false
        type: string
        default: "latest"
        description: 'Additional tag to add to docker image'


jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Github Container Repository
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: trimBranchName
        name: trim branch name if necessary
        run: |
          export branchTag="${{ github.ref_name }}"
          trimTag="${branchTag##*/}"
          echo "BRANCH_TAG=$trimTag" >> $GITHUB_OUTPUT

      - name: Extract metadata (tags, labels) for Docker
        id: meta_pr
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ghcr.io/${{ github.repository }}-${{ inputs.BUILD_TARGET }}
          tags: |
            type=schedule
            type=raw,value=${{ steps.trimBranchName.outputs.BRANCH_TAG }}
            type=ref,event=tag
            type=raw,value=${{ inputs.TAG }}
          
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./${{inputs.BUILD_TARGET}}
          push: true
          tags: ${{ steps.meta_pr.outputs.tags }}
          labels: ${{ steps.meta_pr.outputs.labels }}

    
