permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:
    inputs:
      BUILD_TARGET:
        type: choice
        description: 'Name of project to build'
        options:
          - vdyp-web-ui
        required: true
      TAG:
        required: false
        type: string
        default: "latest"
        description: 'Additional tag to add to docker image'


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Github Container Repository
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./${{inputs.BUILD_TARGET}}
          push: true
          tags: ${{inputs.BUILD_TARGET}}:${{inputs.TAG}}

    
