name: Build and Deploy to Openshift Target Environment
permissions:
  contents: read

on:
  workflow_call:
    inputs:
      target_environment:
        required: true
        type: string
      tag:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      target_environment:
        description: Target environment to deploy to
        required: true
        default: dev
        options:
          - dev
      tag:
        description: Tag to deploy; use SemVer or PR Number
        required: true
        type: string

concurrency:
  # Cancel if re-attempted
  group: ${{ github.event_name }}
  cancel-in-progress: true

jobs:
  call-shared:
    uses: ./.github/workflows/openshift-shared.yml
    secrets: inherit
    with:
      target_environment: ${{ inputs.target_environment }}
      ref:  ${{ github.ref }}
      tag: ${{ inputs.tag }}
