name: Openshift DB deploy/update
run-name: Deploy PostgresCluster to ${{ inputs.ENVIRONMENT_NAME}}

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT_NAME:
        required: true
        type: choice
        options:
          - dev
          - test
          - prod

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.ENVIRONMENT_NAME }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: copy crunchydb files
        run: mkdir staging && cp -r charts/crunchy-postgres staging/crunchy-postgres
      
      - name: Fill properties files
        uses: cschleiden/replace-tokens@v1.2
        with:
          files: staging/**/*
        env:
          LICENSE_PLATE: 'c50504'
          #Vault path is different for prod than all other environments
          #VAULT_RESOURCE: ${{ inputs.ENVIRONMENT_NAME == 'prod' && 'prod' || 'nonprod'  }}
          NAMESPACE: ${{ secrets.oc_namespace }}
          ENV: ${{ inputs.ENVIRONMENT_NAME }}
          DB_STORAGE: ${{ vars.DB_STORAGE }}
          DB_MAX_CPU: ${{ vars.DB_MAX_CPU }}
          DB_MAX_MEMORY: ${{ vars.DB_MAX_MEMORY}}
          DB_REPLICAS: ${{ vars.DB_INSTANCE_HA_REPLICAS }}
          DB_WAL_VOLUME_SIZE: ${{ vars.DB_WAL_VOLUME_SIZE }}
          DB_BACKUP_VOLUME_SIZE: ${{ vars.DB_BACKUP_VOLUME_SIZE }}
          BOUNCER_REPLICAS: ${{ vars.DB_LOADBALANCER_HA_REPLICAS}}
          COMS_DB_USER: ${{ vars.COMS_DB_ROLE}}
          COMS_DB_NAME: ${{ vars.COMS_DB_DATABASE}}
          BATCH_DB_USER: ${{ vars.BATCH_DB_ROLE}}
          BATCH_DB_NAME: ${{ vars.BATCH_DB_DATABASE}}
          #S3_ENVIRONMENT: ${{ inputs.ENVIRONMENT_NAME == 'dev' && 'dev'  || (inputs.ENVIRONMENT_NAME == 'test' && 'tst' || (inputs.ENVIRONMENT_NAME == 'prod' && 'prd' || inputs.ENVIRONMENT_NAME)) }}

      - name: install helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh

      #Explicit install of oc cli tool
      - name: Install oc
        uses: redhat-actions/oc-installer@v1

      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: https://api.silver.devops.gov.bc.ca:6443
          openshift_token: ${{secrets.oc_token}}
          namespace: ${{ secrets.oc_namespace }}

      - name: zip and install helm chart
        run: |
          cd staging && tar -czvf crunchy-postgres.tar.gz crunchy-postgres
          helm upgrade -i crunchy-postgres-${{inputs.ENVIRONMENT_NAME}} ./crunchy-postgres.tar.gz
