name: Deploy Using Maven and Helm
permissions:
  contents: read
on:
  workflow_call:
    inputs:
      target_environment:
        required: true
        type: string
      ref:
        required: false
        type: string

jobs:
  # https://github.com/bcgov-nr/action-builder-ghcr
  builds:
    name: Builds
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        package: [backend, frontend]
    timeout-minutes: 10
    steps:
      - uses: bcgov-nr/action-builder-ghcr@v2.2.0
        with:
          keep_versions: 50
          package: ${{ matrix.package }}
          tag: ${{ github.event.number }}
          tag_fallback: latest
          triggers: ('${{ matrix.package }}/')

  # https://github.com/bcgov/quickstart-openshift-helpers
  deploys:
    name: Deploys
    needs: [builds]
    uses: ./.github/workflows/.deployer.yml
    secrets: inherit
    with:
      environment: ${{ inputs.target_environment }}
      ref: ${{ inputs.ref || 'main' }}  # fallback if ref is not provided
      values: "values-${{ inputs.target_environment }}.yaml"
      triggers: ('backend/' 'frontend/')
      params: |
        --set global.secrets.persist=false \

  # tests:
  #   name: Tests
  #   if: needs.deploys.outputs.triggered == 'true'
  #   needs: [deploys]
  #   uses: ./.github/workflows/.tests.yml
  #   with:
  #     target: ${{ github.event.number }}

  results:
    name: PR Results
    needs: [builds, deploys]
    if: always() && (!failure()) && (!cancelled())
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Success!"
