name: Promote existing release to production

on:
  release:
    types: [released]

permissions:
  contents: read

jobs:
  promote:
    permissions:
      contents: read
      packages: write
    if: github.event.release.prerelease == false
    uses: ./.github/workflows/openshift-target-environment.yml
    secrets: inherit
    with:
      target_environment: prod
      source_sha: ${{ github.sha }}
      release_version: ${{ github.event.release.tag_name }}
